const quotes = ['arka 0 pogon 2 ',
'czyli jutro nie ma streama bo do Warszawy jedziesz ',
'czyli jutro nie ma streama bo do ukraina jedziesz ',
'Czy kobieta zasluguje na milosc ',
'jaki typ kobiet twój ulubiony ',
'jakie lubisz kobiet ',
'mądry facet z ciebie adik 5221 v 3 ',
'tematem Klaudia ',
'jestem koscierzyna ',
'powiedz mi jak mam żyć ',
'jakie lubisz pytanie ',
'jacy handlowcy są najlepsi ',
'jak to jest zakochanie ',
'faceci lubią właśnie takie dziewczyny Klaudia i ',
'Schudnij do Sylwestra Klaudia i Kamil dziewczyny ',
'Najgorsze, co możesz dać kobiecie, to czas ',
'gdzie wysłać i jak napisać Mikołaja adik5221v3: ',
'ja się tobą skarbie kochanie zajmę Klaudia ',
'lubie kobiety lubie chyba kamila milu0407: ',
'Trzeba docenić rolę kobiet w formacji seminaryjnej ',
'Dość użerania się z babami ',
'Ja nie dyskryminuje kobiet ',
'Nie wiesz nic o disco polo ',
'Przygotujcie się. Stefaccio właśnie dołączył(a) na serwer. ',
'jestes głupi discord ',
'znaczy ja jedyne kogo nie lubię to ciapatych i rosja niemcy ',
'ja chyba mądry facet ',
'najnormalniejszy na tym czacie to jest ja krzysztof 2019 ',
'ty chyba gej szymektm6666: ',
'ile pączków może jeść pies ',
'Jak samotny mężczyzna odczuwa samotność ',
'ja fan kobiety ',
'Jak zapamiętać słowa w języku obcym na zawsze ',
'Tylko ze wzgledu na jestes piekna kobieta klaudia tutaj siedze ',
'podoba mi sie nie chyba klaudia 03 03 2019 rok ',
'kurwa duzo mowi klaudia ja nie malo mowi kurwa ',
'Kiedy ślub Tego dnia powiesz TAK Klaudia i ',
'przyznanie się do bycia gejem jest w Polsce trudne ',
'nie wkurwiać mnie w dzień kobiet ',
'dlaczego kurwa ma dwie dziewczyny kamil ',
'ja tam urodę charakter u kobiety cenię ',
'bardzo lubię dżemem i twarogiem ',
'kurwa zglodnialem ',
'ciężko pisać po polsku ',
'jakie ma ty gust do kobiet Sevaltek ',
'jestes brzydka foremnym DONEK__T ',
'Śliczna jest nie jestes piekna tak ',
'dlaczego czarnych marszach sa głupi kobiety ',
'Jestem niezadowolony z życia - jak sobie z tym poradzić ',
'Dlaczego w związku powinnaś dawać z siebie 50% ',
'nikogo to nie obchodzi, włącz gra ',
'kurwa byla mundial drużyną? Sevaltek ',
'takie pierdolenie że Nawałka do dupy trener tu Guardiola nie pomoże z takimi ciotami na boisku zero zangażowania i umiejętności ',
'kurwa 65 minuta a oni sobie chodzą... kiedyś 118 minuta napierdalanka na bramke przeciwnika i gol murasia, z ktorego wszyscy sie śmiali ze ulaniec ',
'jestes coco jambo warszawa Rollin84 ',
'3 cm to może malo ',
'kobieta rodzi dla 500 zl ',
'teraz mnie bardzo ostro wkurwiłeś fajnyeniek ',
'mialem tylko 0 blondynke 0 szatynki 0 brunetki fajnyeniek: 0 łyse szymektm6666: ',
'jakie słynny las krzyży Rollin84: ',
'jakie jest glupie pytanie ',
'Ja mam swoją zasadę jeśli chodzi o zostanie modem. Że nigdy nie proszę o moda ',
'ja jestem gejem nie 100% Rollin84 ',
'ok nie chce obrazic nikogo tutaj pozdrawiam ',
'dlaczego kobiety sa teraz takie latwe ',
'to wszystko nasza wina. ludzi. bo zamiast to pzrewidziec , to produkujemy masowo te świństwa. a potem już sie nic nie da zrobic. i sami też sie do tego przyczyniamy. dym papierosowy, dezodoranty...powinniśmy chociaz my zrobić coś malego! ograniczyć te szkodliwe rzeczy. a co do innych zanieczyszczeń...jak widze tą reklame domestosa "używaj domestosa codziennie wieczorem"...totalna tragedia. gdyby tak było, to cala woda byłaby...no wiecie. i gleba... wybaczcie, jestem trocheSevaltek ',
'Jak karać krzysztof gdy jest niegrzeczne czariixi: ',
'No dzięki Kladzia musisz z nami wytrzymać do wakacji ',
'macie pozdro nie tusk ',
'co mnie motywuje do oglądać streamy ',
'nie podoba mi sie ma imię kuzyn ',
'nie ma zalety i nie ma wady klaudia ',
'dlaczego malo tylko 40 zl Rollin84 ',
'Gdy mówią Ci, że nie dasz rady stream klaudia ',
'dlaczego mój jest pies wariat ',
'klaudia kamil na nasz Discord! ',
'klaudia jesteś najlepszym dziewczyna , chodź ze mną też na lody ',
'nie ma dziewczyny kot ',
'lubie najbardziej arbuzz Sevaltek ',
'Dobrze, że nie w krakow, największa wieś w Polsce ',
'jestes język bulgarski Mexiders: ',
'poziom gry Austrii był ładnie mówiąc kiepski a nasz również był kiepski ',
'kurwa co robie polska 0 łotwa 0 ',
'Kobiety spełniają się artystycznie w kuchni ',
'Zadawaj jej pytania, które pomogą rozpocząć albo podtrzymać rozmowę Nie ma nic prostszego w rozpoczęciu rozmowy z kobietą niż zadanie jej pytania. Wystarczy zapytać: Ładna pogoda prawda? (szczególnie kiedy pogoda jest brzydka Sevaltek ',
'rosół pomidorowa żurek kalafiorowa grochówka z dyni ogórkowa to jedna z najlepszych zup jakie jadłem ',
'każdy kiedyś cierpi. Nie jesteś jedynySevaltek: ',
'Zamiast zachowywać się jak tchórz kończąc ze sobą, weź się do roboty Sevaltek: ',
'Nie dam wam prostej recepty, dla każdego z nas szczęście to coś innego nicecolour ',
'jak wchodze na ten instagram bardzo glodny sie robie ',
'duzo ma uroda 8 nie malo 8 uroda ',
'8 na 10 dlatego że ma wlosy ruda ',
'ja mam 185 i ważę 85kg, troszkę za dużo ale jest śmiesznie ',
'Cześć przyjacielu Masz dziś dla mnie jakieś rady Sevaltek: ',
'skąd się remixon18: w ogóle na twitchu wziął? ',
'Czy nazwa choroby "odra" ma związek z rzeką ',
'Mi się coś nie podoba to daje łapkę w dół, unsub i tyle ',
'Kotek robi miał miał, a krowa robi mu mu. ',
'lepiej mnie nie wkurwiać oglądać stream ',
'jakie zwierze wydaje odglos kle kle i kra kra i bee bee i chrum chrum ',
'No dobra, ale nie ma potwierdzenia z punktu naukowego co jaki dźwięk Reidowiczka: ',
'codziennie sobie zadaje to pytanie co ja tu jeszcze robie na tym świecie ',
'Czy należy życzyć smacznego ',
'ja jezyka obcego ze nie ogarnia totalnie ',
'Dziewczyny nie poderwiesz w żaden żałosny sposób Musisz po prostu być sobą. Jeżeli ona tego nie zrozumie nie jest Ciebie warta Vctr_ ',
'jakie lubisz lody mam lista sondę ',
'jestem mądry chociaż w to nie wierzę ',
'Dlaczego życie bez kobiety jest lepsze od życia z kobietą ',
'Co kurwa To ja tyle ogląda stream ',
'Hugo nie robi loda Sevaltek: ',
'Bo ty nic nie rozumiesz Sevaltek ',
'przepraszam za mój zły polski ',
'co jeśli Sevaltek nie istnieje ',
'ja niego na własne nie oczy Widziałem czariixi ',
'Co mam zrobić aby mój pies przestał szczekać ',
'Mój pies ciągnie na smyczy Co robić ',
'Co zrobić, żeby moj pies nie szczekał ciągle na gości ',
'Czy to normalne, że mój pies wszędzie za mną chodzi ',
'tak obiektywnie dałbym 28 lat klaudia ',
'tak obiektywnie dałbym 35 lat kamil ',
'jeden tylko kurwa ja krzysztof adik5221v3: ',
'odczep ty się od mojego gustu do kobiet twój jest nie leprzy chevre13 ',
'a ja się z tobą nie zgadzam do 9 00000000 chevre13 ',
'kurwa bardzo papa chevre13: ',
'ale nie bardzo śpiewaj proszę klaudia ',
'że jeszcze mój gust nie jest aż tak zły ',
'Nie bo zasnę jeszcze i będziecie podsłuchiwać mnie jak śpie ',
'Nie chcemy dyskusji bez kobiet ',
'Nie będę Was dziś zanudzać stream ',
'Kobiety nie są tutaj po to, żeby się do was uśmiechać ',
'lepiej mnie nie wkurwiać na dzień Chłopaka ',
'Ty chłopak czy facet i ty dziewczyna czy kobieta Rollin84 ',
'tusk cham jestes ',
'Krzysztof ma 33 potwierdzone info z biblii zapytaliście sie ile krzysztof ma lat ',
'Kamil kobieta Ci się zepsuła ',
'stream jest nudne w pewnym momencie ',
'bardzo nie kobiety gorsza rasa rzorzyko ',
'Jak chronić się przed osami ',
'jak jestes z zabrza to na pewno boli cie dupa ',
'kot sam w domu, czyli co robi kot pod Twoją nieobecność kamil ',
'wcześniej mi sie nudziło ale teraz gdy z tobą pisze jest super Sevaltek ',
'jestes blondynka Sevaltek ',
'Czy kogoś pojebało ',
'Banowanie za pisanie głupot jest jeszcze głupsze niż ich pisanie, bo odstrasza dziewczyny ',
'JA SZANUJE dziewczyny piekne kobiety piękne ',
'jestes głupi hugo Sevaltek ',
'Rozmowa między dwoma inteligentnymi osobnikami facetow Sevaltek: ',
'jutro 100% ja naprawiony adik5221v3: ',
'co jest barabasz ',
'mowi dziewczyna mi Gościu weź idź sie napij sobota jest discord ',
'mowi duzo kamil kasztanach O 1000 ',
'powinna szukac klaudia nowy facet ',
'Halo przyjacielu, jesteś Rollin84 ',
'Zaczynam się martwić o Ciebie przyjacielu ? Daj znak życia Rollin84 ',
'Poznać chciałem Ciebie Bo ponoć z Tobą można konie kraść MattDeGhost ',
'Można się z Tobą świetnie bawić, jesteś świetnym towarzyszem MattDeGhost ',
'polki wloszki są zajebiste szczególnie kobiet ',
'Z ryb to najbardziej lubię RYBNE FILETY RYBNE ',
'bardzo lubie ciastka jeżyki kokosowe ',
'jestem nie gejem ',
'Taka kiełbasa z grilla, hot dogi, zapiekanki. Sam bym zjadł coś takiego ',
'bardzo się szanuję MattDeGhost ',
'miesiączki kobiet najgorzej znoszą kobieta ',
'Najgorsze, co możesz dać kobiecie, to czas ',
'klaudia moderator to by był piękny widok ',
'dostanie ja nie bana na tym streamie ',
'ja lubie duzo keczupow ',
'bardzo papa wam wszystkim dziewczyny kobiety ',
'jak kobieca stream to krzysztof ptak wpadnie ',
'bardzo mam dobry gust kobiet ',
'inteligencja jest jak mięśnie, wymaga stałego użycia ',
'ja wyznaczam trendy klaudia ',
'Klaudia już śpiewałaś chyba nie dzisiaj ',
'moja mama kurwa ogladac .twitch.tv/ ',
'Dlaczego dziewczyny na discord nie odpisują i jak to zmienić ',
'Nie ma mężczyzn i kobiet Są ludzie ',
'ja mam tylko 100 gacie i 100 skarpet ',
'Ale nie martwcie się miłe panie. Kobieta jest przecież najlepszym przyjacielem człowieka. Choć niektórzy twierdzą, że po psie. ',
'ja jestem nie google ',
'mam nadzieję że mi się będzie śniła jakaś 18 latka moze 30 latka ',
'bardzo kurwa Sevaltek: mówię że nie lubię facetów ',
'jak śpiewa bardzo to dość Klaudia ',
'Krzysiu bardzo jest zbyt dobry by miec kobiete',
'najgorszy smrod jaki moze byc gowno pies',
'kurwa bardzo mi sie podoba nastolatki lubiecreampie:',
'lechia kurwa świnia Rollin844',
'jestes życie związany kamil',
'moj pies nie ma dziewczyna',
'duzo dni mi Zbanowano',
'mam nie talent jezyka obcego',
'jest tu jakieś kobiety dziewczyny',
'jestes tak głupi tusk',
'dziewczyny kobiety zawsze muszą komplikować',
'Zapodasz jakąś nutę podaj tytuł jakiejś piosenki tylko nie żadne czy doda czy co tam jest teraz na topie',
'Krzychu pójdzie nie bardzo',
'ale bym zjadła taką zapiekanke',
'piszcie dalej piszcie',
'bardzo lubie schabowy z ziemniaczkami i mizeriom',
'Jakie Kobiety lubią mężczyźni? Seksowne, Dziewczyny z sąsiedztwa czy zwyczajne?',
'Musimy przestać nazywać kobiety dziewczynami',
'jak mamy nazywać kobiety kobiety',
'bardzo mi sie podoba byla magdalena zuk',
'wszystkie te zaginione kobiety były bardzo piekne Czemu nikt nie morduje grubych ropuch zamist tych ładnych',
'jestem facet Ciacho',
'lubie Makowiec lubisz klaudia Makowiec',
'klaudia Ty to się kurwa za robotę weź w Twoim wieku',
'Żadna gwałtu nie lubi kobiety Sevaltek',
'Zapraszamy moj Discord!',
'Polski trudna bardzo jestes język',
'zrobiłbyś kolacje kobiete kamil',
'Jakie najbardziej lubicie Pierogi',
'Najbardziej lubie z jabłkami lub truskawkami Lubie też z mięsem',
'lubie nastolatki szatynki piekne pan_kacperek',
'pupa Sevaltek:',
'bardzo mi sie podoba strona',
'mam to samo z mama ja zawsze jestem winny',
'lubie piosenkarki Natalia Szroeder Taylor Swift demi lovato Marta Gałuszewska Monika Lewczuk Natalia Nykiel Sylwia Przybysz Honorata Skarbek Sylwia Lipka Sarsa',
'nie rozumiem ciebie facet bobbydials212',
'szczęście ma kot',
'ja ogladac seriale',
'przykro jak mi tak Verónica Cortés Guadalupe umarła DONEK__T',
'lubie nie kurwa kobiety pan_kacperek',
'Czy pieniądze naprawdę nie dają szczęścia?',
'Po prostu nigdy nie miałem kobiety i nie czuję potrzeby tego zmieniać. Dobrze mi jest samemu',
'Jak uczyć się, żeby nie zapomnieć jezyka obcego',
'Jak zapamiętać słowa w języku obcym na zawsze',
'jak to jest miec kot dobrze',
'jestes piekna ma kot klaudia',
'tak nowy krzysztof 2020 co roku nowe konto',
'lubie na ile % go 50 Sevaltek:',
'lubie klaudia na ile % go 1000',
'nie lubię to ciapatych i rosja niemcy tusk',
'chyba nie ma Talent klaudia',
'ty nie jest kurwa MattDeGhost',
'4-4-3 myśle że najlepsza formacja dla Ekstraklasa',
'Banowanie za pisanie głupot jest jeszcze głupsze niż ich pisanie, bo odstrasza dziewczyny i kobiety Rollin844:',
'jeszcze jak lubie bardzo kobiety dziewczyny Sevaltek:',
'moj jestes nie kot marcepanka Sevaltek:',
'Co jest nie tak z polskimi facetami',
'ciężko pisać po polsku',
'duzo mam wady',
'Cześć przyjacielu Masz dziś dla mnie jakieś rady Rollin844',
'kurwa nie zycie ma kot',
'Nagroda to jest randka w ciemno z kamil',
'czy wam sie podoba natalia brak tvp sport',
'ja bardzo dobre ma tylko tematy',
'Jak nie zostać pantoflarzem',
'jestes piekna kobieta Rollin844:',
'eres una mujer hermosa klaudia',
'que idiomas sabe DONEK__T:',
'Nauka języków Sam zacząłem uczyć się',
'niektórzy nie potrafią docenić piękna muzyki',
'zapodaj ktoś jakąś fajną nutę',
'kamil masz przeprosic krzysia',
'ale donek tez ma przeprosic krzysia',
'ale klaudia tez musi przeprosic krzysia',
'ja kurwa mam 185 waze 85 kg DONEK__T',
'bardzo lubisz mowi kurwa duzo klaudia',
'lubie nie szpinak',
'lubie galaretkę chałwę, batoniki lody pączki chipsy na pewno cos jeszcze do pisze',
'Taka kiełbasa z grilla, hot dogi, zapiekanki. Sam bym zjadł coś takiego',
'mi tam nie szkoda bardzo nauczycieli',
'gdzie klaudia pracuje jeśli to nie jest tajemnica zawodowa',
'Mam ochotę na lody',
'mialem tylko 0 blondynke 0 szatynki 0 brunetki fajnyeniek',
'smacznego btw, jedzeniu sałatki dla klaudii',
'ale Rollin 844 bardzo ma dziś gadane',
'końcu ktoś docenił mnie',
'T Tak tak. Kochaj klaudia kamil',
'Bo nie ma dżemu miroslaw19centymetrowy',
'angielski malo tylko 32 % to się umie sparky69pl',
'jestes kobieta sparky69pl:',
'Będą tu kiedyś jakieś kobiety',
'nie śpimy',
'Zaginęła 17-letnia Patrycja. Trop prowadzi do Berlina Widziałeś dziewczynę ze zdjęcia .fakt.pl/ Skontaktuj się z policją',
'jestes piekna dziewczyna nie ładna DONEK__T',
'kurwa wola kobiety',
'pies towarzyszy swojemu panu, wylegując się w pobliżu.',
'Pewnie znowu będę spał do 8 30',
'ja facet głupi',
'głupi ale ciacho Sevaltek:',
'klaudia bardzo smutno ci z powodu wyboru krzysztofa ?',
'klaudia ma charakter taka 10/10',
'jaki jest wasz Krzysiek bardzo niedobra na dziś?',
'tak jesteś bardzo dobra na jutro krzysztof 2019',
'lubie nie brzydki kobiet',
'krzysztofa dawno nie ma jest u ogladac tottenham ajax toothanm @nicecolour',
'a myślisz że w piekle to tylko duzo szatynki kobiety są?',
'Krzysztof jestem nie gejem',
'kurwa jakie traktowanie kamila ja sie nie dziwie ze krzysztof idzie do adzi ja tez nie moge patrzec na to cierpienie krzysztof',
'Przepraszam Kochanie Przepraszam Cię Mój Skarbie Bardzo Cię przepraszam! Wybacz mi, proszę! Słodko przepraszam! Nie gniewaj się, Kotku! Będę już grzeczny Klaudia',
'ranking jestes uroda 6 klaudia',
'1 kaori_i 2 AiSzjaa 3 aaadzia 4 chocolate_puma 5 tyrisftw 6 nicecolour klaudia 7 Doczu',
'czesc kobiety z koscierzyny',
'co za baba zawsze tak jest z babami kobiety nie dziewczyny',
'ja przynajmniej bardzo jest szczery krzysztof',
'jestes nie kobieta szatynka kamil',
'czy wam sie podoba kot',
'jesteś mądry kot',
'2020 roku nowy ranking podoba mi sie kobiety stream',
'przepraszam za zły polski',
'Skąd mogę wiedzieć, kiedy Bóg mówi do mnie bym coś zrobił kamil',
'Wiesz, że nie ma drugiego takiego mężczyzny jak ja',
'jestes bardzo nie brzydka klaudia',
'Jeśli mógłbyś pozbyć się jednej rzeczy z tego świata, co by to było .',
'usunąłbys mnie kamil tak usunąłbys mnie nie klaudia nie nicecolour',
'Dokładnie, mieszkam około 581 km od klaudia',
'Kościerzyna – Kraków. Najszybszy to wariant przez A1 – droga ma długość 581 km i przejazd zajmie nam zazwyczaj 6 godz. 3 min',
'jak to powiedział pewien znany jegomość mialem tylko 0 blondynke 0 szatynki 0 brunetki',
'Mam dla was zagadkę ! chcecie rozwiązać ? jest o owcach i wilkach',
'są dwie owce i dwa wilki na brzegu rzeki. chcą dostać się na drugą stronę łódką, niestety mieści tylko dwa zwierzaki. jeśli po którejkolwiek stronie będzie więcej wilków niż owiec, zjedzą ją. w jakiej kolejności zwierzęta muszą płynąć ? oczywiście wracając na łodzi musi być jedno zwierze =',
'chciałbym bardzo przeprosić za tak duże opóźnienie z moimi wpisami',
'Naukę języków obcych podobno najlepiej zacząć od dobrej motywacji',
'ja stream tylko kurwa ogladac kobiety',
'Ile lat żyją koty',
'Czy kot zawsze spada na cztery łapy',
'najladniejsze imiona u kobiet to jessica i wiktoria',
'najladniejsze imiona facetów to krzysztof i mateusz',
'znałem kiedyś piekna dziewczyna imieniu sandra zapamiętałem ją bo była ekstremalnie piekna',
'Klaudia jest bardzo zdyscyplinowana, dojrzała i zawsze postępuje etycznie. Ma lekko wybuchową naturę, ale za to głęboką skłonność do poświęcenia i oddania. Czasami za wiele chce z siebie dać i staje się nerwowa. Byłaby nieszczęśliwa, gdyby przepuściła okazję, by komuś pomóc. Każde działanie warte zachodu traktuje jak misję. Ma wielu przyjaciół, a każdy znajdzie u niej wsparcie, dobre słowo i wielkie serce. Sama nie oczekuje żadnych pochwał ani wdzięczności. Zawsze szuka usprawiedliwienia złego p',
'Nie startuj do Rosjanek bo nie będziesz się z nimi umiał porozumieć',
'bardzo lubie kabanosa',
'Jak ci powie że jesteś super przyjacielem to spierdalaj dalej nawet niż polska musttochange97'
];

window.onload = () => {
    const quote = document.querySelector(".quote");
    const button = document.querySelector(".newquote");
    (newRandom = () => {
        random = Math.floor(Math.random() * (quotes.length));
        let data = "<span class='name'>krzysiek2019</span>" + ": " + quotes[random]
        quote.innerHTML = data;
        document.body.style.backgroundImage = "url(https://source.unsplash.com/random/?nature)";
    })();
    button.addEventListener("click", newRandom);
}