window.onload = () => {
  const quotes = [
    "arka 0 pogon 2 ",
    "czyli jutro nie ma streama bo do Warszawy jedziesz ",
    "czyli jutro nie ma streama bo do ukraina jedziesz ",
    "Czy kobieta zasluguje na milosc ",
    "jaki typ kobiet twój ulubiony ",
    "jakie lubisz kobiet ",
    "mądry facet z ciebie adik 5221 v 3 ",
    "tematem Klaudia ",
    "jestem koscierzyna ",
    "powiedz mi jak mam żyć ",
    "jakie lubisz pytanie ",
    "jacy handlowcy są najlepsi ",
    "jak to jest zakochanie ",
    "faceci lubią właśnie takie dziewczyny Klaudia i ",
    "Schudnij do Sylwestra Klaudia i Kamil dziewczyny ",
    "Najgorsze, co możesz dać kobiecie, to czas ",
    "gdzie wysłać i jak napisać Mikołaja adik5221v3: ",
    "ja się tobą skarbie kochanie zajmę Klaudia ",
    "lubie kobiety lubie chyba kamila milu0407: ",
    "Trzeba docenić rolę kobiet w formacji seminaryjnej ",
    "Dość użerania się z babami ",
    "Ja nie dyskryminuje kobiet ",
    "Nie wiesz nic o disco polo ",
    "Przygotujcie się. Stefaccio właśnie dołączył(a) na serwer. ",
    "jestes głupi discord ",
    "znaczy ja jedyne kogo nie lubię to ciapatych i rosja niemcy ",
    "ja chyba mądry facet ",
    "najnormalniejszy na tym czacie to jest ja krzysztof 2019 ",
    "ty chyba gej szymektm6666: ",
    "ile pączków może jeść pies ",
    "Jak samotny mężczyzna odczuwa samotność ",
    "ja fan kobiety ",
    "Jak zapamiętać słowa w języku obcym na zawsze ",
    "Tylko ze wzgledu na jestes piekna kobieta klaudia tutaj siedze ",
    "podoba mi sie nie chyba klaudia 03 03 2019 rok ",
    "kurwa duzo mowi klaudia ja nie malo mowi kurwa ",
    "Kiedy ślub Tego dnia powiesz TAK Klaudia i ",
    "przyznanie się do bycia gejem jest w Polsce trudne ",
    "nie wkurwiać mnie w dzień kobiet ",
    "dlaczego kurwa ma dwie dziewczyny kamil ",
    "ja tam urodę charakter u kobiety cenię ",
    "bardzo lubię dżemem i twarogiem ",
    "kurwa zglodnialem ",
    "ciężko pisać po polsku ",
    "jakie ma ty gust do kobiet Sevaltek ",
    "jestes brzydka foremnym DONEK__T ",
    "Śliczna jest nie jestes piekna tak ",
    "dlaczego czarnych marszach sa głupi kobiety ",
    "Jestem niezadowolony z życia - jak sobie z tym poradzić ",
    "Dlaczego w związku powinnaś dawać z siebie 50% ",
    "nikogo to nie obchodzi, włącz gra ",
    "kurwa byla mundial drużyną? Sevaltek ",
    "takie pierdolenie że Nawałka do dupy trener tu Guardiola nie pomoże z takimi ciotami na boisku zero zangażowania i umiejętności ",
    "kurwa 65 minuta a oni sobie chodzą... kiedyś 118 minuta napierdalanka na bramke przeciwnika i gol murasia, z ktorego wszyscy sie śmiali ze ulaniec ",
    "jestes coco jambo warszawa Rollin84 ",
    "3 cm to może malo ",
    "kobieta rodzi dla 500 zl ",
    "teraz mnie bardzo ostro wkurwiłeś fajnyeniek ",
    "mialem tylko 0 blondynke 0 szatynki 0 brunetki fajnyeniek: 0 łyse szymektm6666: ",
    "jakie słynny las krzyży Rollin84: ",
    "jakie jest glupie pytanie ",
    "Ja mam swoją zasadę jeśli chodzi o zostanie modem. Że nigdy nie proszę o moda ",
    "ja jestem gejem nie 100% Rollin84 ",
    "ok nie chce obrazic nikogo tutaj pozdrawiam ",
    "dlaczego kobiety sa teraz takie latwe ",
    'to wszystko nasza wina. ludzi. bo zamiast to pzrewidziec , to produkujemy masowo te świństwa. a potem już sie nic nie da zrobic. i sami też sie do tego przyczyniamy. dym papierosowy, dezodoranty...powinniśmy chociaz my zrobić coś malego! ograniczyć te szkodliwe rzeczy. a co do innych zanieczyszczeń...jak widze tą reklame domestosa "używaj domestosa codziennie wieczorem"...totalna tragedia. gdyby tak było, to cala woda byłaby...no wiecie. i gleba... wybaczcie, jestem trocheSevaltek ',
    "Jak karać krzysztof gdy jest niegrzeczne czariixi: ",
    "No dzięki Kladzia musisz z nami wytrzymać do wakacji ",
    "macie pozdro nie tusk ",
    "co mnie motywuje do oglądać streamy ",
    "nie podoba mi sie ma imię kuzyn ",
    "nie ma zalety i nie ma wady klaudia ",
    "dlaczego malo tylko 40 zl Rollin84 ",
    "Gdy mówią Ci, że nie dasz rady stream klaudia ",
    "dlaczego mój jest pies wariat ",
    "klaudia kamil na nasz Discord! ",
    "klaudia jesteś najlepszym dziewczyna , chodź ze mną też na lody ",
    "nie ma dziewczyny kot ",
    "lubie najbardziej arbuzz Sevaltek ",
    "Dobrze, że nie w krakow, największa wieś w Polsce ",
    "jestes język bulgarski Mexiders: ",
    "poziom gry Austrii był ładnie mówiąc kiepski a nasz również był kiepski ",
    "kurwa co robie polska 0 łotwa 0 ",
    "Kobiety spełniają się artystycznie w kuchni ",
    "Zadawaj jej pytania, które pomogą rozpocząć albo podtrzymać rozmowę Nie ma nic prostszego w rozpoczęciu rozmowy z kobietą niż zadanie jej pytania. Wystarczy zapytać: Ładna pogoda prawda? (szczególnie kiedy pogoda jest brzydka Sevaltek ",
    "rosół pomidorowa żurek kalafiorowa grochówka z dyni ogórkowa to jedna z najlepszych zup jakie jadłem ",
    "każdy kiedyś cierpi. Nie jesteś jedynySevaltek: ",
    "Zamiast zachowywać się jak tchórz kończąc ze sobą, weź się do roboty Sevaltek: ",
    "Nie dam wam prostej recepty, dla każdego z nas szczęście to coś innego nicecolour ",
    "jak wchodze na ten instagram bardzo glodny sie robie ",
    "duzo ma uroda 8 nie malo 8 uroda ",
    "8 na 10 dlatego że ma wlosy ruda ",
    "ja mam 185 i ważę 85kg, troszkę za dużo ale jest śmiesznie ",
    "Cześć przyjacielu Masz dziś dla mnie jakieś rady Sevaltek: ",
    "skąd się remixon18: w ogóle na twitchu wziął? ",
    'Czy nazwa choroby "odra" ma związek z rzeką ',
    "Mi się coś nie podoba to daje łapkę w dół, unsub i tyle ",
    "Kotek robi miał miał, a krowa robi mu mu. ",
    "lepiej mnie nie wkurwiać oglądać stream ",
    "jakie zwierze wydaje odglos kle kle i kra kra i bee bee i chrum chrum ",
    "No dobra, ale nie ma potwierdzenia z punktu naukowego co jaki dźwięk Reidowiczka: ",
    "codziennie sobie zadaje to pytanie co ja tu jeszcze robie na tym świecie ",
    "Czy należy życzyć smacznego ",
    "ja jezyka obcego ze nie ogarnia totalnie ",
    "Dziewczyny nie poderwiesz w żaden żałosny sposób Musisz po prostu być sobą. Jeżeli ona tego nie zrozumie nie jest Ciebie warta Vctr_ ",
    "jakie lubisz lody mam lista sondę ",
    "jestem mądry chociaż w to nie wierzę ",
    "Dlaczego życie bez kobiety jest lepsze od życia z kobietą ",
    "Co kurwa To ja tyle ogląda stream ",
    "Hugo nie robi loda Sevaltek: ",
    "Bo ty nic nie rozumiesz Sevaltek ",
    "przepraszam za mój zły polski ",
    "co jeśli Sevaltek nie istnieje ",
    "ja niego na własne nie oczy Widziałem czariixi ",
    "Co mam zrobić aby mój pies przestał szczekać ",
    "Mój pies ciągnie na smyczy Co robić ",
    "Co zrobić, żeby moj pies nie szczekał ciągle na gości ",
    "Czy to normalne, że mój pies wszędzie za mną chodzi ",
    "tak obiektywnie dałbym 28 lat klaudia ",
    "tak obiektywnie dałbym 35 lat kamil ",
    "jeden tylko kurwa ja krzysztof adik5221v3: ",
    "odczep ty się od mojego gustu do kobiet twój jest nie leprzy chevre13 ",
    "a ja się z tobą nie zgadzam do 9 00000000 chevre13 ",
    "kurwa bardzo papa chevre13: ",
    "ale nie bardzo śpiewaj proszę klaudia ",
    "że jeszcze mój gust nie jest aż tak zły ",
    "Nie bo zasnę jeszcze i będziecie podsłuchiwać mnie jak śpie ",
    "Nie chcemy dyskusji bez kobiet ",
    "Nie będę Was dziś zanudzać stream ",
    "Kobiety nie są tutaj po to, żeby się do was uśmiechać ",
    "lepiej mnie nie wkurwiać na dzień Chłopaka ",
    "Ty chłopak czy facet i ty dziewczyna czy kobieta Rollin84 ",
    "tusk cham jestes ",
    "Krzysztof ma 33 potwierdzone info z biblii zapytaliście sie ile krzysztof ma lat ",
    "Kamil kobieta Ci się zepsuła ",
    "stream jest nudne w pewnym momencie ",
    "bardzo nie kobiety gorsza rasa rzorzyko ",
    "Jak chronić się przed osami ",
    "jak jestes z zabrza to na pewno boli cie dupa ",
    "kot sam w domu, czyli co robi kot pod Twoją nieobecność kamil ",
    "wcześniej mi sie nudziło ale teraz gdy z tobą pisze jest super Sevaltek ",
    "jestes blondynka Sevaltek ",
    "Czy kogoś pojebało ",
    "Banowanie za pisanie głupot jest jeszcze głupsze niż ich pisanie, bo odstrasza dziewczyny ",
    "JA SZANUJE dziewczyny piekne kobiety piękne ",
    "jestes głupi hugo Sevaltek ",
    "Rozmowa między dwoma inteligentnymi osobnikami facetow Sevaltek: ",
    "jutro 100% ja naprawiony adik5221v3: ",
    "co jest barabasz ",
    "mowi dziewczyna mi Gościu weź idź sie napij sobota jest discord ",
    "mowi duzo kamil kasztanach O 1000 ",
    "powinna szukac klaudia nowy facet ",
    "Halo przyjacielu, jesteś Rollin84 ",
    "Zaczynam się martwić o Ciebie przyjacielu ? Daj znak życia Rollin84 ",
    "Poznać chciałem Ciebie Bo ponoć z Tobą można konie kraść MattDeGhost ",
    "Można się z Tobą świetnie bawić, jesteś świetnym towarzyszem MattDeGhost ",
    "polki wloszki są zajebiste szczególnie kobiet ",
    "Z ryb to najbardziej lubię RYBNE FILETY RYBNE ",
    "bardzo lubie ciastka jeżyki kokosowe ",
    "jestem nie gejem ",
    "Taka kiełbasa z grilla, hot dogi, zapiekanki. Sam bym zjadł coś takiego ",
    "bardzo się szanuję MattDeGhost ",
    "miesiączki kobiet najgorzej znoszą kobieta ",
    "Najgorsze, co możesz dać kobiecie, to czas ",
    "klaudia moderator to by był piękny widok ",
    "dostanie ja nie bana na tym streamie ",
    "ja lubie duzo keczupow ",
    "bardzo papa wam wszystkim dziewczyny kobiety ",
    "jak kobieca stream to krzysztof ptak wpadnie ",
    "bardzo mam dobry gust kobiet ",
    "inteligencja jest jak mięśnie, wymaga stałego użycia ",
    "ja wyznaczam trendy klaudia ",
    "Klaudia już śpiewałaś chyba nie dzisiaj ",
    "moja mama kurwa ogladac .twitch.tv/ ",
    "Dlaczego dziewczyny na discord nie odpisują i jak to zmienić ",
    "Nie ma mężczyzn i kobiet Są ludzie ",
    "ja mam tylko 100 gacie i 100 skarpet ",
    "Ale nie martwcie się miłe panie. Kobieta jest przecież najlepszym przyjacielem człowieka. Choć niektórzy twierdzą, że po psie. ",
    "ja jestem nie google ",
    "mam nadzieję że mi się będzie śniła jakaś 18 latka moze 30 latka ",
    "bardzo kurwa Sevaltek: mówię że nie lubię facetów ",
    "jak śpiewa bardzo to dość Klaudia ",
    "Krzysiu bardzo jest zbyt dobry by miec kobiete",
    "najgorszy smrod jaki moze byc gowno pies",
    "kurwa bardzo mi sie podoba nastolatki lubiecreampie:",
    "lechia kurwa świnia Rollin844",
    "jestes życie związany kamil",
    "moj pies nie ma dziewczyna",
    "duzo dni mi Zbanowano",
    "mam nie talent jezyka obcego",
    "jest tu jakieś kobiety dziewczyny",
    "jestes tak głupi tusk",
    "dziewczyny kobiety zawsze muszą komplikować",
    "Zapodasz jakąś nutę podaj tytuł jakiejś piosenki tylko nie żadne czy doda czy co tam jest teraz na topie",
    "Krzychu pójdzie nie bardzo",
    "ale bym zjadła taką zapiekanke",
    "piszcie dalej piszcie",
    "bardzo lubie schabowy z ziemniaczkami i mizeriom",
    "Jakie Kobiety lubią mężczyźni? Seksowne, Dziewczyny z sąsiedztwa czy zwyczajne?",
    "Musimy przestać nazywać kobiety dziewczynami",
    "jak mamy nazywać kobiety kobiety",
    "bardzo mi sie podoba byla magdalena zuk",
    "wszystkie te zaginione kobiety były bardzo piekne Czemu nikt nie morduje grubych ropuch zamist tych ładnych",
    "jestem facet Ciacho",
    "lubie Makowiec lubisz klaudia Makowiec",
    "klaudia Ty to się kurwa za robotę weź w Twoim wieku",
    "Żadna gwałtu nie lubi kobiety Sevaltek",
    "Zapraszamy moj Discord!",
    "Polski trudna bardzo jestes język",
    "zrobiłbyś kolacje kobiete kamil",
    "Jakie najbardziej lubicie Pierogi",
    "Najbardziej lubie z jabłkami lub truskawkami Lubie też z mięsem",
    "lubie nastolatki szatynki piekne pan_kacperek",
    "pupa Sevaltek:",
    "bardzo mi sie podoba strona",
    "mam to samo z mama ja zawsze jestem winny",
    "lubie piosenkarki Natalia Szroeder Taylor Swift demi lovato Marta Gałuszewska Monika Lewczuk Natalia Nykiel Sylwia Przybysz Honorata Skarbek Sylwia Lipka Sarsa",
    "nie rozumiem ciebie facet bobbydials212",
    "szczęście ma kot",
    "ja ogladac seriale",
    "przykro jak mi tak Verónica Cortés Guadalupe umarła DONEK__T",
    "lubie nie kurwa kobiety pan_kacperek",
    "Czy pieniądze naprawdę nie dają szczęścia?",
    "Po prostu nigdy nie miałem kobiety i nie czuję potrzeby tego zmieniać. Dobrze mi jest samemu",
    "Jak uczyć się, żeby nie zapomnieć jezyka obcego",
    "Jak zapamiętać słowa w języku obcym na zawsze",
    "jak to jest miec kot dobrze",
    "jestes piekna ma kot klaudia",
    "tak nowy krzysztof 2020 co roku nowe konto",
    "lubie na ile % go 50 Sevaltek:",
    "lubie klaudia na ile % go 1000",
    "nie lubię to ciapatych i rosja niemcy tusk",
    "chyba nie ma Talent klaudia",
    "ty nie jest kurwa MattDeGhost",
    "4-4-3 myśle że najlepsza formacja dla Ekstraklasa",
    "Banowanie za pisanie głupot jest jeszcze głupsze niż ich pisanie, bo odstrasza dziewczyny i kobiety Rollin844:",
    "jeszcze jak lubie bardzo kobiety dziewczyny Sevaltek:",
    "moj jestes nie kot marcepanka Sevaltek:",
    "Co jest nie tak z polskimi facetami",
    "ciężko pisać po polsku",
    "duzo mam wady",
    "Cześć przyjacielu Masz dziś dla mnie jakieś rady Rollin844",
    "kurwa nie zycie ma kot",
    "Nagroda to jest randka w ciemno z kamil",
    "czy wam sie podoba natalia brak tvp sport",
    "ja bardzo dobre ma tylko tematy",
    "Jak nie zostać pantoflarzem",
    "jestes piekna kobieta Rollin844:",
    "eres una mujer hermosa klaudia",
    "que idiomas sabe DONEK__T:",
    "Nauka języków Sam zacząłem uczyć się",
    "niektórzy nie potrafią docenić piękna muzyki",
    "zapodaj ktoś jakąś fajną nutę",
    "kamil masz przeprosic krzysia",
    "ale donek tez ma przeprosic krzysia",
    "ale klaudia tez musi przeprosic krzysia",
    "ja kurwa mam 185 waze 85 kg DONEK__T",
    "bardzo lubisz mowi kurwa duzo klaudia",
    "lubie nie szpinak",
    "lubie galaretkę chałwę, batoniki lody pączki chipsy na pewno cos jeszcze do pisze",
    "Taka kiełbasa z grilla, hot dogi, zapiekanki. Sam bym zjadł coś takiego",
    "mi tam nie szkoda bardzo nauczycieli",
    "gdzie klaudia pracuje jeśli to nie jest tajemnica zawodowa",
    "Mam ochotę na lody",
    "mialem tylko 0 blondynke 0 szatynki 0 brunetki fajnyeniek",
    "smacznego btw, jedzeniu sałatki dla klaudii",
    "ale Rollin 844 bardzo ma dziś gadane",
    "końcu ktoś docenił mnie",
    "T Tak tak. Kochaj klaudia kamil",
    "Bo nie ma dżemu miroslaw19centymetrowy",
    "angielski malo tylko 32 % to się umie sparky69pl",
    "jestes kobieta sparky69pl:",
    "Będą tu kiedyś jakieś kobiety",
    "nie śpimy",
    "Zaginęła 17-letnia Patrycja. Trop prowadzi do Berlina Widziałeś dziewczynę ze zdjęcia .fakt.pl/ Skontaktuj się z policją",
    "jestes piekna dziewczyna nie ładna DONEK__T",
    "kurwa wola kobiety",
    "pies towarzyszy swojemu panu, wylegując się w pobliżu.",
    "Pewnie znowu będę spał do 8 30",
    "ja facet głupi",
    "głupi ale ciacho Sevaltek:",
    "klaudia bardzo smutno ci z powodu wyboru krzysztofa ?",
    "klaudia ma charakter taka 10/10",
    "jaki jest wasz Krzysiek bardzo niedobra na dziś?",
    "tak jesteś bardzo dobra na jutro krzysztof 2019",
    "lubie nie brzydki kobiet",
    "krzysztofa dawno nie ma jest u ogladac tottenham ajax toothanm @nicecolour",
    "a myślisz że w piekle to tylko duzo szatynki kobiety są?",
    "Krzysztof jestem nie gejem",
    "kurwa jakie traktowanie kamila ja sie nie dziwie ze krzysztof idzie do adzi ja tez nie moge patrzec na to cierpienie krzysztof",
    "Przepraszam Kochanie Przepraszam Cię Mój Skarbie Bardzo Cię przepraszam! Wybacz mi, proszę! Słodko przepraszam! Nie gniewaj się, Kotku! Będę już grzeczny Klaudia",
    "ranking jestes uroda 6 klaudia",
    "1 kaori_i 2 AiSzjaa 3 aaadzia 4 chocolate_puma 5 tyrisftw 6 nicecolour klaudia 7 Doczu",
    "czesc kobiety z koscierzyny",
    "co za baba zawsze tak jest z babami kobiety nie dziewczyny",
    "ja przynajmniej bardzo jest szczery krzysztof",
    "jestes nie kobieta szatynka kamil",
    "czy wam sie podoba kot",
    "jesteś mądry kot",
    "2020 roku nowy ranking podoba mi sie kobiety stream",
    "przepraszam za zły polski",
    "Skąd mogę wiedzieć, kiedy Bóg mówi do mnie bym coś zrobił kamil",
    "Wiesz, że nie ma drugiego takiego mężczyzny jak ja",
    "jestes bardzo nie brzydka klaudia",
    "Jeśli mógłbyś pozbyć się jednej rzeczy z tego świata, co by to było .",
    "usunąłbys mnie kamil tak usunąłbys mnie nie klaudia nie nicecolour",
    "Dokładnie, mieszkam około 581 km od klaudia",
    "Kościerzyna – Kraków. Najszybszy to wariant przez A1 – droga ma długość 581 km i przejazd zajmie nam zazwyczaj 6 godz. 3 min",
    "jak to powiedział pewien znany jegomość mialem tylko 0 blondynke 0 szatynki 0 brunetki",
    "Mam dla was zagadkę ! chcecie rozwiązać ? jest o owcach i wilkach",
    "są dwie owce i dwa wilki na brzegu rzeki. chcą dostać się na drugą stronę łódką, niestety mieści tylko dwa zwierzaki. jeśli po którejkolwiek stronie będzie więcej wilków niż owiec, zjedzą ją. w jakiej kolejności zwierzęta muszą płynąć ? oczywiście wracając na łodzi musi być jedno zwierze =",
    "chciałbym bardzo przeprosić za tak duże opóźnienie z moimi wpisami",
    "Naukę języków obcych podobno najlepiej zacząć od dobrej motywacji",
    "ja stream tylko kurwa ogladac kobiety",
    "Ile lat żyją koty",
    "Czy kot zawsze spada na cztery łapy",
    "najladniejsze imiona u kobiet to jessica i wiktoria",
    "najladniejsze imiona facetów to krzysztof i mateusz",
    "znałem kiedyś piekna dziewczyna imieniu sandra zapamiętałem ją bo była ekstremalnie piekna",
    "Klaudia jest bardzo zdyscyplinowana, dojrzała i zawsze postępuje etycznie. Ma lekko wybuchową naturę, ale za to głęboką skłonność do poświęcenia i oddania. Czasami za wiele chce z siebie dać i staje się nerwowa. Byłaby nieszczęśliwa, gdyby przepuściła okazję, by komuś pomóc. Każde działanie warte zachodu traktuje jak misję. Ma wielu przyjaciół, a każdy znajdzie u niej wsparcie, dobre słowo i wielkie serce. Sama nie oczekuje żadnych pochwał ani wdzięczności. Zawsze szuka usprawiedliwienia złego p",
    "Nie startuj do Rosjanek bo nie będziesz się z nimi umiał porozumieć",
    "bardzo lubie kabanosa",
    "Jak ci powie że jesteś super przyjacielem to spierdalaj dalej nawet niż polska musttochange97",
    "mi Zbanowano cię na tym kanale blondynkitezgraja twitch.tv",
    "zakochany nigdy nie byłem",
    "bardzo lubie Bezglutenowe ciastka z ciecierzycy z czekoladą",
    "jestem w stanie zjeść BARDZO dużo i.... i tak nie przytyje",
    "to krzysiu w szatynki piekne gustuje",
    "moj internet chujowy",
    "Powiedz mi, jakie stream oglądasz, powiem ci, kim jesteś DONEK__T:",
    "dlaczego ranking 1 bardzo podoba uroda ma szatynka ma fajna podoba charakter jestes bardzo piekna kobieta kaori",
    "co bys zrobila byl kobieta kamil",
    "No cóż zrobiłbym wszystko to co dziewczęce nicecolour",
    "ja bardzo lubie tak kobiet",
    "a to od 18 lat sa juz kobiety",
    "ja bym powiedzial ze od 15 lat i 17 sa dziewczyny",
    "czy wami sie podoba bikini kobiet",
    "Zapraszamy moj Discord! krzysztof 2019",
    "Nigdy nie umawiaj się z byłą dziewczyną",
    "mogą stworzyć całkiem dobry związek partnerski. W końcu kto nie zrozumie kobiety tak dobrze jak i ona sama. W takim związku są same zalety. Dziewczyny mogą chodzić razem po sklepach, godzinami gadać o babskich sprawach i w ogóle. ",
    "Kobieta stanie na czele Komisji Europejskiej. Może myślą, że kobiety są mniej pijące. Tuska też może zastąpić niewiasta",
    "od 15 do 17 lat to jest dziewczyna lat to jest 18 to kobieta",
    "lubie nie cie kot klaudia",
    "tusk bardzo od urodzenia jest w ciągu alkoholowym",
    "Nie śpimy",
    "kurwa co ja",
    "dlaczego ma klaudia ogłada, klasa kobieta",
    "el magik: z tobom umowic ty klaudia chyba ryby",
    "dlaczego jest coraz mniej porządnych dziewczyn",
    "czy to prawda że kobiety są bardziej wymagające w doborze partnera w porównaniu do mężczyzn",
    "Myślę że tak. Dlaczego tak się dzieje, nie mam pojęcia. Ale tak jest.",
    "Naucz się najważniejszych słów po norwesku! kavvva92",
    "jak ciebie nie było to był męskie tematy czyli kobiety",
    "przepraszam za słaby polski",
    "powinna papa unii tusk donek t",
    "jesteś jak żart tusk",
    "bardzo jestes słaby DONEK__T:",
    "bardzo dobry mam gust nie ma gust tusk DONEK__T",
    "odczep ty się od mojego gustu do kobiet twój jest nie leprzy DONEK__T",
    "jak układać proste zdania w języku polski",
    "gdybym miał powiedzieć co cenię w życiu najbardziej powiedziałbym że szatynki kobiety",
    "jutro ty się nie tylko odpalasz tusk",
    "nowy 2020 ranking robie ja krzysztof",
    "dlaczego Polski język trudny",
    "bardzo lubie kotleta",
    "kotlety nie ale kobiety lepsze",
    "100 zl + 100 zl =200 zl",
    "co jeść żeby schudnąć raz na zawsze",
    "ja jestem idealny, najpiękniejszy i najwspanialszy na świecie i nie muszę chudnąć ani tyć",
    "jak tam zdróweczko u was",
    "byl bardzo głupie Hitler",
    "Dlaczego kobiety trwają przy socjopatach i manipulatorach",
    "nie ma kraju bez kobiety i dziewczyny",
    "Dziewczyny Cię nie zauważają gran_imperio",
    "Dlaczego współczesna kobieta nie potrafi ułożyć sobie związku",
    "ja piję nie 18 roku życia praktycznie",
    "Ja Bardzo lubię ten kanał. Pewnie dlatego jest klaudia kobieta piekna fajna madra o wszystkim pogadać",
    "kurwa tylko ladna jestes klaudia",
    "Ja tylko gimnazjum skończyłem i ledwo umiem pisać i się troche dziwie dlaczego nie mogę znaleść kobiety",
    "mi nie trzeba kobiety",
    "ja miałem 0 kobiety w życiu",
    "idę spać. Dobranoc wszystkim dziewczyny kobiety",
    "kurwa co ja oglada",
    "bardzo lubie Kanapki szyneczka, ser żółty pomidorek ogóreczek szczypiorek, pietruszka i sałata",
    "bardzo lubie tost kiełbasa kotlet boczek parówki jakieś smażone mięso ser tost jajko sadzone - frytki",
    "Jak emo dziewczyna się zachowuje?",
    "Czy matura jest ważna",
    "zapierdalac trzeba ogladac stream",
    "Ja sie nie oświadcza kobiete nigdy",
    "bierzmowaniu nie byłem i nie planuję a bez tego ślubu kościelnego nie wezmę",
    "dlaczego malo tylko jest takie że 70% to kurwy kobiety",
    "podoba mi sie 1 szatynki blondynki 0 brunetki 0",
    "dlaczego nie rozumiem kot",
    "Ja miałem wyjebane na naukę angielskiego w szkole",
    "Hawajska pizza jest zajebista",
    "Hawajska jest dobra jak się ananasa",
    "Zwierzęta w ZOO cierpią",
    "Krzysiek urodzony w tylko 1988 roku Sevaltek:",
    "kurwa co mowi trener lechia tvp sport",
    "hugo tylko ma 1 lat bobbydials212",
    "warszawa największa wieś w Polsce",
    "lechia gdańsk kurwa świnia Rollin844:",
    "ile w tej kobiete klaudia jest energii krzysztof 2019",
    "kto juz kupil losowanie? Pewnie Tusk nie wygra",
    "ja to zawsze mowie ze nogi to najseksowniejsza czesc ciala u kobiety",
    "Kamil powiedz jej, że pierścionek jest nieważny, najważniejsza jest tylko miłość",
    "jakie miec wspomnienia",
    "Hugo tak chrapiecie bobbydials212:",
    'kamil dziś na discordzie napisał mi "XDDDDDD", a potem zapytał czy wiem co to znaczy',
    "Krzychowi się podoba wszystko mądre szatynki piekne wysokie kobiety",
    "ja nie mówić dobrze po polsku",
    "najpopularniejszy włoski ser jestes Parmezan",
    "bardzo lubie chałwa",
    "jakie ma imie ile ma lat mama klaudia",
    "z kobietami jak zwykle jak z dziećmi czariixi:",
    "nie chce mi sie isc wykąpać co mam zrobic",
    "nie musisz więc nie idź do tej beznadziejnej pracy",
    "ranking orzechów: 1 pistacje 2 ziemne 3 włoskie",
    "Jakieś Ładne Zdrobnienia Do Imienia Klaudia",
    "rządzi ja tylko czat",
    'znaczy że twoje umiejętności wyrażania emocji są ograniczone Jeszcze jak piszesz zdanie i dodajesz na koniec "xD" to spoko Ale sam spam "xDDDDDDDD" to nie świadczy o tobie dobrze DONEK__T:',
    "Czego lepiej nie mówić kobiecie",
    "kurwa malo klaudia spiewanie",
    "jesteś tylko kot",
    "Musimy przestać nazywać kobiety dziewczynami",
    "darmowe jedzie? gdzie? podaj adres już jadę",
    "jedyna wadą warszawa Platforma Obywatelska",
    "Buenos días Mi nombre es Krzysztof czariixi:",
    "Czy polski akcent jest obciachowy",
    "kiedyś miałem inne myślenie kobietach",
    "jestes tyko kot nie pies",
    "klaudia powiedz mi ze mnie bardzo lubisz ok",
    "Dlaczego kobiety traktują się jak rywalki zamiast wspierać się wzajemnie",
    "inter cienkie bolki fajnyeniek:",
    "czy wam nie jest wstyd kiedy facet za was płaci Vctr__:",
    "dlaczego mężczyźni się go boją ślubu",
    "dlaczego On nie chce się żenić kamil",
    "Kto to Trigger_Happy_Hextech",
    "jestes nie romantyzm kamil",
    "Połączenie się z kimś węzłem małżeńskim to z założenia decyzja na całe życie. Jak dowodzą tego rosnące z roku na rok statystyki rozwodów, coraz częściej okazuje się, że ślub nie łączy już ludzi po grobową deskę. Powodem rozstań najczęściej jest zły dobór partnera. A wystarczy na początku znajomości trochę się skupić i zwrócić uwagę na pewne cechy dziewczyny, za którą tak przepadamy. Czy faktycznie ta osoba jest wymarzoną kandydatką no żonę i, być może, matkę naszych dzieci",
    "kiedy facet myśli o żeniaczce wtedy na pewno wybierz tę, która umie gotować kamil",
    "Kobiety znane są z tego, że lubią mówić. Dużo i głośno. Mężczyźni od kandydatki na żonę oczekują, że będzie ona potrafiła zamilknąć, żeby on w tym czasie mógł spokojnie poczytać gazetę albo się zdrzemnąć. Nic tak nie irytuje mężczyzn, jak ciągłe gadanie Namiętność i pożądanie, które towarzyszom początkom związku, z czasem mogą nieco przygasnąć. Dlatego najważniejsze jest, żeby żona była również przyjaciółką. Tego właśnie szukają mężczyźni w kandydatce na życiową partnerkę. Przyjaźni. Bez niej ża",
    "Dobra żona nie zwraca uwagi na innych facetów, bo żaden z nich nie dorównuje Tobie Dobra żona jest Twoją najlepszą przyjaciółką. Potrafi wysłuchać i doradzić Dobra żona czule zajmuje się Waszymi dziećmi Dobra żona przynosi Ci herbatę do łóżka, kiedy masz 38 stopniową gorączkę i umierasz.Dobra żona jest dumna z Twoich osiągnięć zawodowych i wspiera Cię w karierze. Przy każdej okazji komplementuje Cię Dobra żona ma do Ciebie zaufanie Dobra żona broni Cię, gdy ktoś Cię krytykuje, a Ty wiesz, że moż",
    "czy powtórz ten ruch jeszcze raz, aby go utrwalić? Tak, tak, powtórka jest świetna, szczególnie wtedy kiedy jest OD RAZU. Kończysz czytać rozdział książki- przejrzyj go szybko jeszcze raz. Skończyłeś notować jakieś informacje, przejrzyj swoje notatki zanim zamkniesz zeszyt. Wychodzisz z wykładu– zrób w głowie szybkie podsumowanie itd. Jeśli tego nie robisz, większość informacji ulotni się z Twojego mózgu w ciągu 24 godzin klaudia",
    "głupie tematy ma tusk",
    "piszcie dalej piszcie czat",
    "Ta piękna kobieta jest już zajęta ty klaudia czat",
    "też jestem piękny a nikt się we mnie nie zakochał",
    "słoń podobny jestes tusk",
    "czesc kot",
    "bardzo lubie Brzoskwinia",
    "Klaudia zawsze pięknie wygląda, bo jest tylko nie ładna piekna",
    "Czemu mówimy „pierogi ruskie”, chociaż to polskie jedzenie",
    "Co najbardziej jest potrzebne do życia",
    "ja robie badania co 3 miesiac i sa bardzo dobre",
    "ale juventus lech poznań to serdecznie proszę mi nie obrażać bo w ryj mogę dać",
    "Kobiety tak myślą bardzo facetow nie myślą",
    "Co się stanie, gdy będę jeść tylko owoce",
    "imie nie ma takie głupie",
    "Czy psa należy kąpać",
    "kurwa krakow",
    "ale kościerzyna to serdecznie proszę mi nie obrażać bo w ryj mogę dać",
    "ja spię po 8 godziny dziennie",
    "Kim są i czego chcą feministki",
    "sa glupie chyba kobiety feministki",
    "lubie duzo szatynki lubie malo blondynki lubie chyba brunetki",
    "najbardziej normalny na tym stream to jestem ja",
    "ciekawe czy Polska będzie w unii do następnych wyborów ty nie tusk DONEK__T",
    "nie dyskutuj z kobietą kamil",
    "jestes hugo czarną owcą w rodzinie",
    "potem się dziwisz, że Cię facet nie szanuje klaudia",
    "zdrowe placuszki jogurtowe z bananem🍌🥞. Proste, smaczne i zdrowe. Od razu dzień staje się piękniejszy, gdy takie śniadanko zagości na stole. ➡️Składniki:",
    "gdzie moje maniery. Smacznego klaudia",
    "ile płacicie alimentów na jedno dziecko kot",
    "Każdy z nas od czasu do czasu popełnia błędy. Bywa też, że swoimi czynami albo zachowaniami skrzywdzimy innych ludzi. W takich sytuacjach ważne jest, aby potrafić przyznać się do błędu i powiedzieć “przepraszam",
    "Co zrobić kiedy życie wydaje się bez sensu",
    "uwielbiam naleśniki, placki, placuszki, omlety",
    "jeśli zasnę to przepraszam",
    "ale jestem takim samym człowiekiem,jak nie patrzę kto ile ma kasa",
    "no trochę nudno jestes stream",
    "Wypadanie włosów Nie trać głowy gejczarodziej666:",
    "COOO TAK WCZEŚNIE LAJWIK? A JAAAK :D WPADAJ MORDKO :D #NAŻYWO #MAHONEK #RAFONIX #OME.TV",
    "kot wiem że chyba tak żyje",
    "odoba mi sie kobiety stream moj Ranking 1 madziula 2 kaori_i 3 AiSzjaa 4 nicecolur 5 malinovvaa 6 WscieklaAlpaka 7 Doczu 8 korneelcia 9 chocolate_puma",
    "list do Ciebie list do Ciebie napisał ty Świętego Mikołaja do DONEK__T:",
    "byla 1 2 wojna światowa ale nasze kobiety życie to 3 Maroserabre:",
    "jakie lubisz Kiełbasa",
    "lubie nie pieczarki",
    "potrzeba 1200 godzin nauki języka obcego, by osiągnąć w nim tzw. niezależność językową – czyli komunikować się bez barier. Przeliczmy – 1200 godzin oznacza godzinę dziennie przez ponad trzy lata lub ponad 3 godziny dziennie przez rok. To bardzo długo.",
    "mowi klaudia i nie bedzie na razie bo klaudia jest zla na kamil i niech sobie kamil prowadzi stream",
    "tematy kurwa tylko ryby stream",
    "Panga co naprawdę w niej siedzi",
    "Panga ryba egzotyczna ryba trucizna - ku przestrodze",
    "bardzo szkoda że nie mogę przyjechać do Krakowa bo bym przyjechał Ci e przytulił bardzo klaudia",
    "ja bardzo lubie oglądać nice colour ta polska kobieta",
    "lubie dobra kakao siema DONEK__T",
    "tusk jestes rok ma najebany",
    "ja nie umiem pisać",
    "jak nauczyć pisać",
    "Mógłbym się w niej zakochać cie klaudia",
    "nie mam przyjaciół",
    "lekcja na dziś, nie rozmawiać z Rosjanami",
    "Po co wymyślono internet",
    "dasz radę bardzo ja tak Kladzia, wierzymy w ciebie",
    "Kladzia kiedy idziemy na lody",
    "kup mi auto kamil",
    "parady wolności kobiety od Krzysztofa trzeba zorganizować",
    "jestes bardzo głupi discord",
    "zaloz konto aby zachowac wszystkie serwery i wiadomosci nawet po zamknieciu przegladarki discord",
    "cos sie tutaj dzieje wykrylismy cos nietypowego aby uzywac dalej discorda musisz potwierdzic ze jestes czlowieklem dlaczego mi",
    "co mowi kurwa czat",
    "Dlaczego czat sprawia mi przykrość",
    "przykrości tak sprawia czat",
    "dlaczego jestes nie romantyk kamil",
    "Dama ta wywodziła się z bogatej szlachty, jednak spory majątek, jakiego dorobił się jej dziadek, została roztrwoniona (także na skutek przemian politycznych) przez Tomasza Łęckiego, ojca Izabeli. Pomimo tego, nie przejmowała się ona coraz gorszą sytuacją materialną, lecz starała się wykorzystać każdą okazję, by wieść – tak bardzo jej miłe – życie salonowe. Izabela miała w zwyczaju obracać się w naprawdę wysokich kręgach, m.in. w towarzystwie Wiktora Emanuela (króla Italii).Vctr__",
    "moj Ranking 1 madziula 2 kaori_i 3 AiSzjaa 4 malinovvaa 5 Doczu 6 WscieklaAlpaka 7 kornelcia 8 chocolate_puma 9 nicecolur",
    "tylko 4 uroda jestes klaudia",
    "dyskryminacja mężczyzn",
    "jestem nie pani",
    "mnie tez boli jakies chujstwo z ta pogoda dzisiaj",
    "jestes madra facet kamil",
    "mam nadzieję że osoba odpowiedzialna za te upały zostanie wyjebana z mojego miasta i niech spierdala do brazylia",
    "już po 22 daj sąsiadom nie spać",
    "Co tak naprawdę dzieje się na wieczorze kawalerskim",
    "ja pije piwo tak mając 18 lat i mi nie pasowało to był pierwszy i ostatni alkohol w moim życiu",
    "Czego żałujemy przed śmiercią?",
    "Ja po hiszpańsku umiem niña mujer casa madre no tan ale to mi nie pomoże",
    "jestes nie kaleka klaudia",
    "cos sie tutaj dzieje wykrylismy cos nietypowego aby uzywac dalej discorda musisz potwierdzic ze jestes czlowiekiem",
    "Nie ma to jak z dziewczyną pogadać o bejsbolu w ciepła noc stream xNiuNia",
    "że bym Ci ją pokazał to byś jej nie zobaczył bo jej nie mam kobiete bobbydials212:",
    "ja oglądam i pilka nozna i ciebie ale ty ważniejsza",
    "tak się porobiło że znaleźć kobiete inteligentna już trudno",
    "Kurwa, aborcja powinna być uzależniona od indywidualnej decyzji kobiety nie",
    "Najgorsze, co możesz dać kobiecie, to czas",
    "poziom gry Austrii był ładnie mówiąc kiepski a nasz również był kiepski",
    "ale nie bardzo śpiewaj proszę klaudia",
    'Czy nazwa choroby "odra" ma związek z rzeką',
    "lubie galaretkę chałwę, batoniki lody pączki chipsy na pewno cos jeszcze do pisze",
    "Jak uczyć się, żeby nie zapomnieć jezyka obcego",
    "ja bardzo dobre ma tylko tematy",
    "Ja mam swoją zasadę jeśli chodzi o zostanie modem. Że nigdy nie proszę o moda",
    "Jak nie zostać pantoflarzem",
    "lubie klaudia na ile % go 1000",
    "jak śpiewa bardzo to dość Klaudia",
    "chyba ze mną nie dobrze że komentuję co widzę na ekranie",
    "Co do aborcji mam mieszane uczucia",
    "sami zwolennicy 500+ jestes kobiet jestes mężczyzn",
    "Liczba mnoga w języku angielskim jak ją tworzymy",
    "Gdybym miał kobiete to dbałbym o nią, pomógłbym jej, wspierał bym ją",
    "Znowu zdycham, bez przerwy gorąco jak sam skurwysyn",
    "lubie kompotu jabłek gruszek wisni nicecolour",
    "sa tu jakie kobiety czat",
    "Mi to się wydaje, że do całe głosowanie to klaudia ustawił",
    "Jak ci powie że jesteś super przyjacielem to spierdalaj dalej nawet niż polska",
    "4-4-3 myśle że najlepsza formacja dla Ekstraklasa",
    "Czy kobieta zasluguje na milosc",
    "co za baba zawsze tak jest z babami kobiety nie dziewczyny",
    "ciężko pisać po polsku",
    "dziewczyny kobiety zawsze muszą komplikować",
    "Jak kobiety chciałyby być traktowane nie są",
    "mi kobiety nie trzeba",
    "czesc Moobot:",
    "czesc kot",
    "Feministki to nie są normalne kobiety przecież",
    "no tak najgorsze 9 miesięcy w życiu faceta i kobieta",
    "Kobiety w Polsce i Europie są lepiej wykształcone niż mężczyźni. Ale co z tego, skoro w pensji jakoś tego nie widać",
    "jestes bardzo głupi konto discord",
    "Jak całkowicie usunąć konto Discord",
    "mam 30 lat, wielbiciel kobiet i szatynek, fan piłki nożnej i amator dobrych streamów juventus top girls",
    "znaczy ja jedyne kogo nie lubię to ciapatych i rosja niemcy",
    "Musimy przestać nazywać kobiety dziewczynami",
    "No krzys zle mowil o dziewczynach kobietach Ale ogólnie Krzyś jest super",
    "No Klaudia powiedziała źle na krzsia bo Krzyś obraża dziewczyny kobiety",
    "Nie wolno obrażać kobiet a wiele feministek to dobre kobiety które chcą by innym kobietom było lepiej",
    "Dlatego Klaudia się zdenerwowała bo kobietom trzeba pomagać a nie je obrażać. Rozumiesz",
    "Tusk nie ma szacunku do kobiet",
    "wieku 10 lat ja rozgladac sie za dziewczynami",
    "Perła – marka piwa produkowanego przez browar w Lublinie należący do firmy Perła – Browary Lubelskie. Dostępne jest w butelkach zwrotnych, a także bezzwrotnych o pojemności 0,5 oraz 0,3 litra oraz w puszkach. Rollin844",
    "Za taką cenę pewnie i plecy umyje 1000000 zł DONEK__T:",
    "Czy kiedykolwiek, kłócąc się z osobą płci przeciwnej, miałeś wrażenie, że kompletnie przekręca jakieś zdarzenie z przeszłości",
    "Są kobiety na chwilę i kobiety na całe życie",
    "zycie ma niedobry kot",
    "BARDZO SILNY WIATR I INTENSYWNE BURZE Z GRADEM W ZACHODNIEJ, CENTRALNEJ I PÓŁNOCNEJ POLSCE",
    'jaka jest ładna śliczna piekna brzydką angelika remixon18"',
    "dlaczego malo tylko 500 zl",
    "pięknie dziś wyglądasz, miłego streamka i pozdrawiam z rodzinką i kotami",
    "Co to znaczy być romantycznym i kim jest romantyczny mężczyzna",
    "jaka jestes pogoda krakow",
    "mi Obfite opady deszczu",
    "kim jestes Nightbot",
    "kurwa nie jestem Bot",
    "dlaczego malo piszcie dalej piszcie",
    "Dlaczego świętujemy Boże Ciało",
    "Czego nie potrafią zrozumieć faceci",
    "Czego mężczyźni nie lubią w kobietach",
    "to nie lubię w dziewczynach Nic nie irytuje bardziej niż dziewczyny, które toczą z ciebie bekę i powtarzają, że mają dystans do siebie, a po jednym żarcie skierowanym w ich stronę, obrażają się na wieki. Niektóre dziewczyny mają święte przekonanie o swojej racji. Nawet, gdy chcesz im dać radę, to biorą to za złośliwą uwagę i nie dają tobie dojść do słowa.",
    "Brak rozmowy może być końcem małżeństwa",
    "niektórzy nie potrafią docenić piękne kobiety",
    "jak tam zdróweczko u was",
    "Taka kiełbasa z grilla, hot dogi, zapiekanki. Sam bym zjadł coś takiego",
    "bardzo lubie tost kiełbasa kotlet boczek parówki jakieś smażone mięso ser tost jajko sadzone - frytki",
    "jak układać proste zdania w języku polski",
    "Ja tylko gimnazjum skończyłem i ledwo umiem pisać i się troche dziwie dlaczego nie mogę znaleść kobiety",
    "Ja miałem wyjebane na naukę angielskiego w szkole",
    "gdańska kurwa świnia Rollin844:",
    "jak układać proste zdania w języku polski",
    "Kamil. Mam sprawę",
    "Jak zrozumieć cokolwiek z hiszpanski",
    "Czy odgadniemy Twój ulubiony smak lodów czariixi:",
    "Ja ma 0 euro ale muszę wymienić w kantorze",
    "czy oglądanie filmów,/bajek/kreskówek w obcym języku, którego się wcześniej w ogóle nie uczyło pomaga na osłuchanie się w nim i wpływa jakoś na dalszą naukę? czy to nie ma sensu, jeśli się nic nie rozumie? zamierzam oglądać tek kreskówki, łatwiej się domyślić o co chodzi.. tylko nie wiem, czy aby to nie strata czasu i najpierw rozpocząć naukę opanować chociaż podstawowe słownictwo i dopiero wtedy wziąć się za oglądanie czegokolwiek.",
    "nie mam dziewczyny mam pies",
    "no dobra ale po co w stream oglądacie czat",
    "to jest mój lodówka już jest sprzedany tylko czeka na mnie bobbydials212",
    "Chyba zawsze bede samotny",
    "Będą tu kiedyś jakieś kobiety",
    "Dlaczego dziewczyny na discord nie odpisują i jak to zmienić",
    "klaudia gdybym miał powiedzieć co cenię w życiu najbardziej powiedziałbym że szatynki piekne kobiety",
    "Jak zapamiętać słowa w języku obcym na zawsze",
    "już śpiewałaś chyba nie dzisiaj",
    "ciężko pisać po polsku",
    "lubie piwo",
    "ale bym się piwa napił",
    "piekna klaudia przy tobie noc jest jak dzien pozniewan tak proieniuje twoja piekna uroda",
    "Przepraszam Kochanie Przepraszam Cię Mój Skarbie Bardzo Cię przepraszam! Wybacz mi, proszę! Słodko przepraszam! Nie gniewaj się, Kotku! Będę już grzeczny Klaudia",
    "najbardziej normalny na tym stream to jestem ja",
    "Hawajska pizza jest zajebista",
    ": ja nie umiem pisać",
    "bardzo mi sie piosenka Legia to ch*je a Lech mistrz Polski (wersja 10 minutowa) Rollin844:",
    "Jestem niezadowolony z życia - jak sobie z tym poradzić",
    "przepraszam za słaby polski",
    "wszystkie te zaginione kobiety były bardzo piekne Czemu nikt nie morduje grubych ropuch zamist tych ładnych",
    "jak układać proste zdania w języku polski",
    "Krzysiu bardzo jest zbyt dobry by miec kobiete",
    "jest takie że 30% to nie kurwy kobiety",
    "mnie tez boli jakies chujstwo z ta pogoda dzisiaj",
    "nie dyskutuj z kobietą kamil",
    "bardzo lubie Kanapki szyneczka, ser żółty pomidorek ogóreczek szczypiorek, pietruszka i sałata",
    "Są kobiety na chwilę i kobiety na całe życie",
    "bardzo papa wam wszystkim dziewczyny kobiety",
    "czy wam nie jest wstyd kiedy facet za was płaci Vctr",
    "bardzo lubie barszcz",
    "ja jestem Krzysiek bardzo dobra na dziś",
    "kim jest M N I E !",
    "Czemu do mnie dzwonisz klaudia discord",
    "Prawdziwy facet musi mieć co najmniej kilka kobiet",
    "Dlaczego nie mam snów",
    "Dlaczego zapominamy, co nam się śniło",
    "Dlaczego mężczyźni wybierają złe dziewczyny?",
    "Dlaczego my faceci nie rozumiem kobiety",
    "Ja bym się nudził z taką całkowicie normalną kobiety",
    "Nie krzywdzić kot",
    "ale nie bardzo śpiewaj proszę klaudia",
    "ja przynajmniej bardzo jest szczery krzysztof",
    "Dlaczego życie bez kobiety jest lepsze od życia z kobietą",
    "Ja sie nie oświadcza kobiete nigdy",
    "ja tam lubię patrzeć jak kobiety biją się o facetow piękny widok",
    "kurwa nie rozumie ja krzysiek nicecolour",
    "jestes bardzo piekna kot",
    "Nie traćcie nadziei, nigdy",
    "kurde jak ja bardzo lubie twoje streamy tylko tu sa poruszane takie zyciowe tematy szanuje was za to",
    "ja nie cieszę w pełni jak coś",
    "ja mogę iść z Tobą na randkę do klaudia",
    "Jak całkowicie usunąć konto Discord",
    "Nie startuj do wloszki bo nie będziesz się z nimi umiał porozumieć",
    "krzyś +!",
    "myślisz że w piekle to tylko duzo szatynki kobiety są",
    ":( :D >( :| O_o HolidayTree",
    "Mi piaci davvero Me gustas mucho I really like klaudia",
    "tak obiektywnie dałbym 28 lat klaudia",
    "najlepsze są bombowe kobiety na dyskotekach",
    "Dlaczego współczesna kobieta nie potrafi ułożyć sobie związku",
    "Oj takie coś to ja uwielbiam pyszności biszkopt Coś suchy Ci biszkopt wyszedł Klaudia",
    "lubie Chlebki",
    "Są kobiety na chwilę i kobiety na całe życie",
    "Na tym świecie już nie ma wartościowych mężczyzn Też tak myślisz",
    "Ja bym chciał zmienić świata ale nie tak jakby każdy chiał",
    "Ja to was szanuję normalna piekna madra kobieta ,normalny facet zamieszkali sobie w kawalerce Tyle ludzi streamuje z kobieta na twitchu ,a ten chłop zawsze skurwysyn buffon. A tu normalna para w końcu",
    "Kto nie może oddać krwi ja",
    "Nie umawiam się z dziewczynami. Mam swoje powody",
    "Co dziewczyna ma na myśli mówiąc chłopakowi Nie jesteś w moim typie",
    "dziewczyny kobiety zawsze muszą komplikować",
    "dlaczego kobiety sa teraz takie latwe",
    "Którego pseudonimu literackiego nie używała Maria Konopnicka",
    "Czy kogoś pojebało mi nie Nicecolour",
    "ja mam tak urodzin w tym roku",
    "ja pije piwo tak mając 18 lat i mi nie pasowało to był pierwszy i ostatni alkohol w moim życiu",
    ": ale juventus lech poznań to serdecznie proszę mi nie obrażać bo w ryj mogę dać",
    "bardzo lubie Bezglutenowe ciastka z ciecierzycy z czekoladą",
    "nie jestem ginekologiem Rollin844:",
    "mogą stworzyć całkiem dobry związek partnerski. W końcu kto nie zrozumie kobiety tak dobrze jak i ona sama. W takim związku są same zalety. Dziewczyny mogą chodzić razem po sklepach, godzinami gadać o babskich sprawach i w ogóle.",
    "jeśli zasnę to przepraszam",
    "zapierdalac trzeba ogladac stream",
    "Co jest nie tak z polskimi facetami",
    "No krzys zle mowil o dziewczynach kobietach Ale ogólnie Krzyś jest super",
    "dlatego facet w domu byc musi bo kobieta + kuchnia = niebezpieczenstwo",
    "ja mam inne pytanie dlaczego kogoś interesuj kiedy facet chodzi nie ginekologa",
    "chcę dożyć 100 lat",
    "Legia to huje a lech mistrz polski!",
    "Dlaczego kobiety traktują się jak rywalki zamiast wspierać się wzajemnie",
    "Nom, też tak postrzegam, sam rozróżniam kobiety od dziewczyn ale nie umiem powiedzieć czym się przy tym kieruję",
    "czy tylko ja ich nie rozumiem kobiet",
    "wszystkie seriale oglądam po hiszpansku",
    "you are usa england krynnec:",
    "Nie jesteś kurwa z USA krynnec",
    "Dlaczego mężczyźni mają piwne brzuchy, kobiety nie",
    "O czym mężczyzna chciałby Ci powiedzieć ale mu głupio",
    "chyba ma raka klaudia",
    "KOT jestes nie adam małysz",
    "duzo duzo duzo duzo duzo mowi mowi mowi mowi kurwa kurwa kurwa kurwa kurwa kurwa kurwa klaudia",
    "Dlaczego pies i kot się nie lubią",
    "mowi czat krzysztof to samiec alfa dajcie mu spokój",
    "mowi czat krzysztof ty dziku",
    "ogólnie to każda stream kobieta moja",
    "jestem atrakcyjna madry facet",
    "lubie kebab",
    "CHEMIA między kobietą facetem Co to właściwie jest",
    "Jak chcą wyglądać dzisiaj wszystkie kobiety",
    "Czy zasługujesz na piękną kobiete kamil",
    "Skąd wiadomo, że to już koniec miłości brzytfa",
    "dlaczego malo mowi kurwa kamil",
    "jak kobieca stream to krzysztof ptak wpadnie",
    "gdybym miał powiedzieć co cenię w życiu najbardziej powiedziałbym że szatynki piekne kobiety",
    "Kobiety spełniają się artystycznie w kuchni",
    "Ja tylko gimnazjum skończyłem i ledwo umiem pisać i się troche dziwie dlaczego nie mogę znaleść kobiety",
    "Dwie muchy jedzą gówno. Jedna mówi - ale śmierdzi, na to druga bo z cebulą nicecolour",
    "nie rozumie życia klaudia",
    "nigdy się nie pytaj dziewczyny czy jest coś z tobą nie tak, bo to znaczy że się nie szanujesz.",
    "przeciez krzysio jest uroczy mi mowi stream czat",
    "Mogę pożyczyć twój telefon? Po co Bo chcę zadzwonić do mamy i powiedzieć jej, że znalazłam kobiete swoich marzeń. MattDeGhost:",
    "inteligencja jest jak mięśnie, wymaga stałego użycia",
    "mezczyzni zawsze woli młodsze kobiety",
    "najbardziej normalny na tym stream to jestem ja",
    "polki wloszki są zajebiste szczególnie kobiet",
    "jak nauczyc sie myslec po angielsku",
    "anglia anglia anglia anglia selicja",
    "tylko kobieta zrozumie kobieta",
    "jesteś facet nie kobieta kamil",
    "Jak dobrze wychować dziecko w The Sims 4",
    "Kobieta doniosła sama na siebie, że się modliła w pracy",
    "chyba ze mną nie dobrze że komentuję co widzę na ekranie",
    "kamil nie bedzie zmywac pewnie HEHE",
    "jestes ty nie kurwa czariixi",
    "Dać coś kobiecie- od razu popsuje",
    "kanapeczki ogarnięte, można oglądać dalej",
    "Krzysztof jest zielony",
    "legia warszawa chuj",
    "Kurwa ale pierogów najebała",
    "kurwa nie więcej Kamila kurwa nie więcej Kamila kurwa nie więcej Kamila kurwa nie więcej Kamila",
    "jak powinna wyglądać dobrze przeprowadzona lekcja jezyka obcego",
    "Co takiego kobiety nie rozumieją w mężczyznach",
    "jestes piosenka Blue Café",
    "krzysztof na dziś zadaje ważne pytania",
    "mi polki nie trzeba",
    'kim jest moderatora"?',
    "jeśli chodzi o dzisiaj obecnych moderatorów to krzysztof 2019 zdecydowanie na pierwszym miejscu",
    "lubie piernik",
    "KOMPROMITACJA LEGII! Remis na Gibraltarze trafia na listę hańby",
    "miałem kłopot z gramatyką",
    "klaudia kobieta to jest klaudia kobieta nie ma takiego drugiego",
    "jestes tyko kot",
    "dlaczego robie nie dzieci kamil",
    "czesc kot",
    "Zakochać się przez internet",
    "Jak pozbyć się poczucia, że nic nie lubię robić",
    "bardzo lubie zarcie",
    "Dlaczego język polski jest tak diabelnie trudny",
    "Czy pisania można się nauczyć",
    "Co piąty człowiek nie potrafi czytać i pisać",
    "jak odkryc swój zyciowy cel",
    "byl bardzo głupie zle Hitler remixon18",
    "Jaka kobieta nadaje się na żonę",
    "Kiedy kobieta ma za wysokie libido",
    "co to znaczy jak dziewczyna chłopaka pociaga",
    "Ja jestem mądry po kawie nie glupi jak widzę kobietę taką piekna",
    "ja przypierdoli do kobity jakiejs stream",
    "jestem inteigentna",
    "ja tak myślałem sobie kiedyś, że niegłupio byłoby zrobić wesele w jakimś fajnym miejscu typu np. wlochy czy coś, i zaprosić np szatynki",
    "Ronaldinho poślubił dwie kobiety jednocześnie",
    "Ja to bym ślub nie wział tak kolacje",
    "lubie Makowiec",
    "masz jakies fajne i normalne kobiety w mieście",
    "tatuowanie inicjałów swojego chłopaka/dziewczyny to juz totalna głupota",
    "Gol jest wtedy, kiedy piłka całym swoim obwodem przekroczy odległość równą obwodowi piłki nicecolour",
    "dlaczego nie ma facetow okresu",
    "Klaudia mnie tam inne kobiety niz ty na tym czacie nie interesuja",
    "Zawsze mówię, że trzeba poczuć magię",
    "Ile śpi kot Od czego to zależy",
    "ja tylko kurwa ogladac jutro Ekstraklasa stream",
    "Tylko ze wzgledu na jestes piekna kobieta klaudia tutaj siedze",
    "Dlaczego w związku powinnaś dawać z siebie 50%",
    "tak się porobiło że znaleźć kobiete inteligentna już trudno",
    "lubie ja nie moja mama krzyczy",
    "Czemu faceci się tak bardzo denerwują, kiedy kobiety płaczą",
    "musisz byc strasznie niedowartosciowana kobieta jesli wybralas takiego partnera klaudia",
    "weź tu zrozum kobiety dziewczyny",
    "Czym się różni brunetka od szatynki? 90% ludzi nie zna odpowiedzi",
    "ja nie mówić dobrze po polsku",
    "jestes ok czat",
    "czy powiedzieć dwie, obie dziewczęta, czy dwoje oboje dziewcząt",
    "jestes mój typ ale piekna jest Rollin844",
    "ja jebie kobieto tu się nic takiego nie dzieje nawet a ty skaczesz dlaczego",
    "Nie każda facet, ma w kuchni instynkt",
    "przede wszystkim faceci są lepszymi kucharzami",
    "duzo mowi kamil kamil kamil kamil kamil",
    "może mi krzysztof krzysztof krzysztof",
    "Do najbliższych imienin Krzysztofa zostały 3 dni",
    "Nie startuj do wloszki bo nie będziesz się z nimi umiał porozumieć",
    "kup mi mózg",
    "no czasem w szmateksie można wyrwać kobiety",
    "mam jednego tatę i 1 mamy remixon18",
    "klaudia chcesz sie moze umówić",
    "nie ma zycia kot",
    "Nicecolour Mam jedno zajebiście ważne pytanie i proszę pozwól mi to zrozumieć: Czemu kobiety zawsze wybierają chujów i prostaków a ten miły zawsze trafia do friendzone",
    "dziewczyny kobiety zawsze muszą komplikować",
    "jak ja bym chcial miec znowu 8 lat",
    "dlaczego głupia jestes czariixi",
    "lubie nie lubie lubie nie Klaudia Dlaczego dlaczego dlaczego zaczyna krzyczeć Klaudia zaczyna krzyczeć Klaudia zaczyna krzyczeć",
    "Dlaczego Święty Mikołaj rozdaje prezenty",
    "lubie nie kurwa pani",
    "w w polsce usa duzo grubasek i nie dbaja o sobie",
    "https://clips.twitch.tv/create",
    "Kamil krzyknij legia to chuje a lech poznan mistrz",
    ", ja bardzo męski mężczyzna",
    "Kamil kobieta Ci się zepsuła",
    "Kto w waszym związku nosi spodnie?",
    "Nie mam tego w dupie",
    "Czy mężczyzna może być feministą",
    "Najgorsze, co możesz dać kobiecie, to czas",
    "klaudia powiedz mi ze mnie bardzo lubisz ok",
    "bardzo lubie ciastka jeżyki kokosowe",
    "ja jezyka obcego ze nie ogarnia totalnie",
    "polki wloszki są zajebiste szczególnie kobiet",
    "Gdybym miał kobiete to dbałbym o nią, pomógłbym jej, wspierał bym ją",
    "Krzysztof powinien byc Prezes PZPN",
    "idź już spać dzamdzamyt:",
    "nie ma nowy https://krzysiek90969.github.io/krzysiek-na-dzis/",
    "Czy pies może mieć ADHD",
    "moj ma pies ADHD",
    "jestes kurwa discord",
    "Ile trzyma piwo po jakim czasie schodzi, ile ma promili NicolasBrown98:",
    "mam 30 na karku i nigdy nie byłem zakochany",
    "jestem w stanie zjeść BARDZO dużo i.... i tak nie przytyje",
    "nie chce mi sie isc wykąpać co mam zrobic",
    "jak ciebie nie było to był męskie tematy czyli kobiety JedenRowerTrzyPedaly",
    "jestem zdania że życie ludzkie należy chronić, chciałbym żeby kobiety rozważały aborcję jako OSTATECZNOŚĆ a w miarę możliwości, jeżeli nie chcą takiego dziecka oddawały je do np. domów dziecka",
    "Po aborcji nadal jest się kobieta",
    "Zwierzę wpadł mi dziś do domu",
    "żaba wpadł mi dziś do domu",
    "Jestem kibicem juventusu od 1997 roku, wieku ośmiu lat zakochałem sie w tej drużynie i kibicuje im dziś i zawsze",
    "jestes nie ciacho kamil",
    "kakałko Disappearer:",
    "Czego pragną kobiety to pytanie, na które mężczyźni szukają odpowiedzi od wieków",
    "Rosja podobnie nie sprawia, że kobiety czują się szczególnie bezpiecznie,",
    "Jeśli podobają Ci się jakieś Rosjanki, koresponduj z kilkoma.",
    "przemocy domowej doświadcza co piąta Rosjanka, a po zmianie przepisów sprawcy są karani symbolicznie",
    "dlaczego teraz młode dziewczyny chyba sa takie glupie",
    "Skąd się bierze dobry gust",
    "parady wolności kobiety od Krzysztofa trzeba zorganizować",
    "Ja miałem wyjebane na naukę angielskiego w szkole",
    "Dlatego Klaudia się zdenerwowała bo kobietom trzeba pomagać a nie je obrażać. Rozumiesz",
    "Krzysiu bardzo jest zbyt dobry by miec kobiete",
    "Szalona kobieta i Kamilu jej facet. Jak idą postępy ze jezyka hiszpanski Cały czas czekam ogólnie co słychać co dziś pijemy",
    "Księżniczki bez zainteresowań, które wybierają brutali. Tak mężczyźni oceniają polskie kobiety ie mają zainteresowań, są księżniczkami, oczekują nierealnego, są zakompleksione – oto, co Polacy myślą o Polkach. Współczesnym kobietom zarzucają również... wybieranie nieodpowiednich partnerów",
    "Po co właściwie ludzie się żenią?",
    "jakby było dużo ludzi to byłaby lipa, nie widziałbym wtedy wiadomości od kobiet dziewczyn",
    "chyba nie śmierdzi hugo kot nie śmierdzi?",
    "dlaczego kot śmierdzi",
    "coś w tym jest jak byłem młody piłem hektolitry mleka, teraz mam 1185 cm i mega mocne kości",
    "lesbijki są okej ale gejów nie toleruje Kappa",
    "Przecież na Kamila nie będzie każda leciała",
    "Ty Nic Nie Rozumiesz.",
    "krzysztof eksperta od kobiety dziewczyny",
    "liczy się kobiet 1 uroda 2 charakter",
    "ja tylko mam racje chevre13",
    "mnie do seksu nie ciągnie tak jak was",
    "Ja tam wierny stream kobiety mi nie trzeba",
    "papa 30 lat mam 31 lat",
    "najlepszego Krzysiu. Powiedz dzień dobry 31 lat",
    "podoba mi sie telenowela W obronie honoru Tierra de reyes"
  ];

  const quote = document.querySelector(".quote");
  const button = document.querySelector(".newquote");
  (newRandom = () => {
    random = Math.floor(Math.random() * quotes.length);
    let data =
      "<span class='name'>krzysztof2019</span>" + ": " + quotes[random];
    quote.innerHTML = data;
    document.body.style.backgroundImage =
      "url(https://source.unsplash.com/random/?nature)";
  })();
  button.addEventListener("click", newRandom);
};
