const quotes = ['arka 0 pogon 2 ',
'czyli jutro nie ma streama bo do Warszawy jedziesz ',
'czyli jutro nie ma streama bo do ukraina jedziesz ',
'Czy kobieta zasluguje na milosc ',
'jaki typ kobiet twój ulubiony ',
'jakie lubisz kobiet ',
'mądry facet z ciebie adik 5221 v 3 ',
'tematem Klaudia ',
'jestem koscierzyna ',
'powiedz mi jak mam żyć ',
'jakie lubisz pytanie ',
'jacy handlowcy są najlepsi ',
'jak to jest zakochanie ',
'faceci lubią właśnie takie dziewczyny Klaudia i ',
'Schudnij do Sylwestra Klaudia i Kamil dziewczyny ',
'Najgorsze, co możesz dać kobiecie, to czas ',
'gdzie wysłać i jak napisać Mikołaja adik5221v3: ',
'ja się tobą skarbie kochanie zajmę Klaudia ',
'lubie kobiety lubie chyba kamila milu0407: ',
'Trzeba docenić rolę kobiet w formacji seminaryjnej ',
'Dość użerania się z babami ',
'Ja nie dyskryminuje kobiet ',
'Nie wiesz nic o disco polo ',
'Przygotujcie się. Stefaccio właśnie dołączył(a) na serwer. ',
'jestes głupi discord ',
'znaczy ja jedyne kogo nie lubię to ciapatych i rosja niemcy ',
'ja chyba mądry facet ',
'najnormalniejszy na tym czacie to jest ja krzysztof 2019 ',
'ty chyba gej szymektm6666: ',
'ile pączków może jeść pies ',
'Jak samotny mężczyzna odczuwa samotność ',
'ja fan kobiety ',
'Jak zapamiętać słowa w języku obcym na zawsze ',
'Tylko ze wzgledu na jestes piekna kobieta klaudia tutaj siedze ',
'podoba mi sie nie chyba klaudia 03 03 2019 rok ',
'kurwa duzo mowi klaudia ja nie malo mowi kurwa ',
'Kiedy ślub Tego dnia powiesz TAK Klaudia i ',
'przyznanie się do bycia gejem jest w Polsce trudne ',
'nie wkurwiać mnie w dzień kobiet ',
'dlaczego kurwa ma dwie dziewczyny kamil ',
'ja tam urodę charakter u kobiety cenię ',
'bardzo lubię dżemem i twarogiem ',
'kurwa zglodnialem ',
'ciężko pisać po polsku ',
'jakie ma ty gust do kobiet Sevaltek ',
'jestes brzydka foremnym DONEK__T ',
'Śliczna jest nie jestes piekna tak ',
'dlaczego czarnych marszach sa głupi kobiety ',
'Jestem niezadowolony z życia - jak sobie z tym poradzić ',
'Dlaczego w związku powinnaś dawać z siebie 50% ',
'nikogo to nie obchodzi, włącz gra ',
'kurwa byla mundial drużyną? Sevaltek ',
'takie pierdolenie że Nawałka do dupy trener tu Guardiola nie pomoże z takimi ciotami na boisku zero zangażowania i umiejętności ',
'kurwa 65 minuta a oni sobie chodzą... kiedyś 118 minuta napierdalanka na bramke przeciwnika i gol murasia, z ktorego wszyscy sie śmiali ze ulaniec ',
'jestes coco jambo warszawa Rollin84 ',
'3 cm to może malo ',
'kobieta rodzi dla 500 zl ',
'teraz mnie bardzo ostro wkurwiłeś fajnyeniek ',
'mialem tylko 0 blondynke 0 szatynki 0 brunetki fajnyeniek: 0 łyse szymektm6666: ',
'jakie słynny las krzyży Rollin84: ',
'jakie jest glupie pytanie ',
'Ja mam swoją zasadę jeśli chodzi o zostanie modem. Że nigdy nie proszę o moda ',
'ja jestem gejem nie 100% Rollin84 ',
'ok nie chce obrazic nikogo tutaj pozdrawiam ',
'dlaczego kobiety sa teraz takie latwe ',
'to wszystko nasza wina. ludzi. bo zamiast to pzrewidziec , to produkujemy masowo te świństwa. a potem już sie nic nie da zrobic. i sami też sie do tego przyczyniamy. dym papierosowy, dezodoranty...powinniśmy chociaz my zrobić coś malego! ograniczyć te szkodliwe rzeczy. a co do innych zanieczyszczeń...jak widze tą reklame domestosa "używaj domestosa codziennie wieczorem"...totalna tragedia. gdyby tak było, to cala woda byłaby...no wiecie. i gleba... wybaczcie, jestem trocheSevaltek ',
'Jak karać krzysztof gdy jest niegrzeczne czariixi: ',
'No dzięki Kladzia musisz z nami wytrzymać do wakacji ',
'macie pozdro nie tusk ',
'co mnie motywuje do oglądać streamy ',
'nie podoba mi sie ma imię kuzyn ',
'nie ma zalety i nie ma wady klaudia ',
'dlaczego malo tylko 40 zl Rollin84 ',
'Gdy mówią Ci, że nie dasz rady stream klaudia ',
'dlaczego mój jest pies wariat ',
'klaudia kamil na nasz Discord! ',
'klaudia jesteś najlepszym dziewczyna , chodź ze mną też na lody ',
'nie ma dziewczyny kot ',
'lubie najbardziej arbuzz Sevaltek ',
'Dobrze, że nie w krakow, największa wieś w Polsce ',
'jestes język bulgarski Mexiders: ',
'poziom gry Austrii był ładnie mówiąc kiepski a nasz również był kiepski ',
'kurwa co robie polska 0 łotwa 0 ',
'Kobiety spełniają się artystycznie w kuchni ',
'Zadawaj jej pytania, które pomogą rozpocząć albo podtrzymać rozmowę Nie ma nic prostszego w rozpoczęciu rozmowy z kobietą niż zadanie jej pytania. Wystarczy zapytać: Ładna pogoda prawda? (szczególnie kiedy pogoda jest brzydka Sevaltek ',
'rosół pomidorowa żurek kalafiorowa grochówka z dyni ogórkowa to jedna z najlepszych zup jakie jadłem ',
'każdy kiedyś cierpi. Nie jesteś jedynySevaltek: ',
'Zamiast zachowywać się jak tchórz kończąc ze sobą, weź się do roboty Sevaltek: ',
'Nie dam wam prostej recepty, dla każdego z nas szczęście to coś innego nicecolour ',
'jak wchodze na ten instagram bardzo glodny sie robie ',
'duzo ma uroda 8 nie malo 8 uroda ',
'8 na 10 dlatego że ma wlosy ruda ',
'ja mam 185 i ważę 85kg, troszkę za dużo ale jest śmiesznie ',
'Cześć przyjacielu Masz dziś dla mnie jakieś rady Sevaltek: ',
'skąd się remixon18: w ogóle na twitchu wziął? ',
'Czy nazwa choroby "odra" ma związek z rzeką ',
'Mi się coś nie podoba to daje łapkę w dół, unsub i tyle ',
'Kotek robi miał miał, a krowa robi mu mu. ',
'lepiej mnie nie wkurwiać oglądać stream ',
'jakie zwierze wydaje odglos kle kle i kra kra i bee bee i chrum chrum ',
'No dobra, ale nie ma potwierdzenia z punktu naukowego co jaki dźwięk Reidowiczka: ',
'codziennie sobie zadaje to pytanie co ja tu jeszcze robie na tym świecie ',
'Czy należy życzyć smacznego ',
'ja jezyka obcego ze nie ogarnia totalnie ',
'Dziewczyny nie poderwiesz w żaden żałosny sposób Musisz po prostu być sobą. Jeżeli ona tego nie zrozumie nie jest Ciebie warta Vctr_ ',
'jakie lubisz lody mam lista sondę ',
'jestem mądry chociaż w to nie wierzę ',
'Dlaczego życie bez kobiety jest lepsze od życia z kobietą ',
'Co kurwa To ja tyle ogląda stream ',
'Hugo nie robi loda Sevaltek: ',
'Bo ty nic nie rozumiesz Sevaltek ',
'przepraszam za mój zły polski ',
'co jeśli Sevaltek nie istnieje ',
'ja niego na własne nie oczy Widziałem czariixi ',
'Co mam zrobić aby mój pies przestał szczekać ',
'Mój pies ciągnie na smyczy Co robić ',
'Co zrobić, żeby moj pies nie szczekał ciągle na gości ',
'Czy to normalne, że mój pies wszędzie za mną chodzi ',
'tak obiektywnie dałbym 28 lat klaudia ',
'tak obiektywnie dałbym 35 lat kamil ',
'jeden tylko kurwa ja krzysztof adik5221v3: ',
'odczep ty się od mojego gustu do kobiet twój jest nie leprzy chevre13 ',
'a ja się z tobą nie zgadzam do 9 00000000 chevre13 ',
'kurwa bardzo papa chevre13: ',
'ale nie bardzo śpiewaj proszę klaudia ',
'że jeszcze mój gust nie jest aż tak zły ',
'Nie bo zasnę jeszcze i będziecie podsłuchiwać mnie jak śpie ',
'Nie chcemy dyskusji bez kobiet ',
'Nie będę Was dziś zanudzać stream ',
'Kobiety nie są tutaj po to, żeby się do was uśmiechać ',
'lepiej mnie nie wkurwiać na dzień Chłopaka ',
'Ty chłopak czy facet i ty dziewczyna czy kobieta Rollin84 ',
'tusk cham jestes ',
'Krzysztof ma 33 potwierdzone info z biblii zapytaliście sie ile krzysztof ma lat ',
'Kamil kobieta Ci się zepsuła ',
'stream jest nudne w pewnym momencie ',
'bardzo nie kobiety gorsza rasa rzorzyko ',
'Jak chronić się przed osami ',
'jak jestes z zabrza to na pewno boli cie dupa ',
'kot sam w domu, czyli co robi kot pod Twoją nieobecność kamil ',
'wcześniej mi sie nudziło ale teraz gdy z tobą pisze jest super Sevaltek ',
'jestes blondynka Sevaltek ',
'Czy kogoś pojebało ',
'Banowanie za pisanie głupot jest jeszcze głupsze niż ich pisanie, bo odstrasza dziewczyny ',
'JA SZANUJE dziewczyny piekne kobiety piękne ',
'jestes głupi hugo Sevaltek ',
'Rozmowa między dwoma inteligentnymi osobnikami facetow Sevaltek: ',
'jutro 100% ja naprawiony adik5221v3: ',
'co jest barabasz ',
'mowi dziewczyna mi Gościu weź idź sie napij sobota jest discord ',
'mowi duzo kamil kasztanach O 1000 ',
'powinna szukac klaudia nowy facet ',
'Halo przyjacielu, jesteś Rollin84 ',
'Zaczynam się martwić o Ciebie przyjacielu ? Daj znak życia Rollin84 ',
'Poznać chciałem Ciebie Bo ponoć z Tobą można konie kraść MattDeGhost ',
'Można się z Tobą świetnie bawić, jesteś świetnym towarzyszem MattDeGhost ',
'polki wloszki są zajebiste szczególnie kobiet ',
'Z ryb to najbardziej lubię RYBNE FILETY RYBNE ',
'bardzo lubie ciastka jeżyki kokosowe ',
'jestem nie gejem ',
'Taka kiełbasa z grilla, hot dogi, zapiekanki. Sam bym zjadł coś takiego ',
'bardzo się szanuję MattDeGhost ',
'miesiączki kobiet najgorzej znoszą kobieta ',
'Najgorsze, co możesz dać kobiecie, to czas ',
'klaudia moderator to by był piękny widok ',
'dostanie ja nie bana na tym streamie ',
'ja lubie duzo keczupow ',
'bardzo papa wam wszystkim dziewczyny kobiety ',
'jak kobieca stream to krzysztof ptak wpadnie ',
'bardzo mam dobry gust kobiet ',
'inteligencja jest jak mięśnie, wymaga stałego użycia ',
'ja wyznaczam trendy klaudia ',
'Klaudia już śpiewałaś chyba nie dzisiaj ',
'moja mama kurwa ogladac .twitch.tv/ ',
'Dlaczego dziewczyny na discord nie odpisują i jak to zmienić ',
'Nie ma mężczyzn i kobiet Są ludzie ',
'ja mam tylko 100 gacie i 100 skarpet ',
'Ale nie martwcie się miłe panie. Kobieta jest przecież najlepszym przyjacielem człowieka. Choć niektórzy twierdzą, że po psie. ',
'ja jestem nie google ',
'mam nadzieję że mi się będzie śniła jakaś 18 latka moze 30 latka ',
'bardzo kurwa Sevaltek: mówię że nie lubię facetów ',
'jak śpiewa bardzo to dość Klaudia '];

window.onload = () => {
    const quote = document.querySelector(".quote");
    const button = document.querySelector(".newquote");
    (newRandom = () => {
        random = Math.floor(Math.random() * (quotes.length));
        let data = "<span class='name'>krzysiek2019</span>" + ": " + quotes[random]
        quote.innerHTML = data;
        document.body.style.backgroundImage = "url(https://source.unsplash.com/random/?nature)";
    })();
    button.addEventListener("click", newRandom);
}